// 友链检测 CLI 需要使用显式导入和相对路径
import type { FeedGroup } from '../app/types/feed'
import { myFeed } from '../blog.config'

export default [
	// #region Clarity
	{
		name: '清晰体验',
		desc: '使用 Clarity 博客主题构建的网站。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			myFeed,
			{
				author: '纸鹿',
				sitenick: '摸鱼处',
				title: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				link: 'https://blog.zhilu.site/',
				feed: 'https://blog.zhilu.site/atom.xml',
				icon: 'https://weavatar.com/avatar/47c0f2e82b76d9b10eb3023df9e02e4e3fdbeaf5b74b842063f207971e7fbe7b?s=160',
				avatar: 'https://weavatar.com/avatar/47c0f2e82b76d9b10eb3023df9e02e4e3fdbeaf5b74b842063f207971e7fbe7b?s=160',
				archs: ['Nuxt', 'Vercel'],
				date: '2024-12-09',
				comment: '纸鹿摸鱼处的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格纸鹿至麓不知路，支炉制露不止漉。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '梦爱吃鱼',
				sitenick: '梦爱吃鱼',
				title: '梦爱吃鱼',
				desc: '但愿日子清静抬头遇见的满是柔情',
				link: 'https://blog.bsgun.cn/',
				feed: 'https://blog.bsgun.cn/atom.xml',
				icon: 'https://lib.bsgun.cn/Hexo-static/img/favicon.ico',
				avatar: 'https://oss-cdn.bsgun.cn/logo/avatar.256.png',
				archs: ['Nuxt', '服务器'],
				date: '2024-12-09',
				comment: '梦爱吃鱼的个人博客。站长当前心境平和，专注于个人表达与创作。文章风格但愿日子清静抬头遇见的满是柔情。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '柒渊阁',
				sitenick: '',
				title: '柒渊阁',
				desc: '柒上月日，无铭之阁',
				link: 'https://www.myxz.top/',
				feed: '',
				icon: 'https://sourceimage.s3.bitiful.net/myxz.avif',
				avatar: 'https://sourceimage.s3.bitiful.net/myxz.avif',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2024-12-09',
				comment: '柒渊阁的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格柒上月日，无铭之阁。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
		],
	},
	// #endregion
	// #region 网上邻居
	{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '朽丘秋雨',
				sitenick: '',
				title: '朽丘秋雨',
				desc: '一定会和喜欢的人在夏日夜晚牵手慢步',
				link: 'https://koxiuqiu.cn/',
				feed: 'https://koxiuqiu.cn/atom.xml',
				icon: 'https://image.lolimi.cn/2025/07/23/6880e2af521da.png',
				avatar: 'https://image.lolimi.cn/2025/07/23/6880e2af521da.png',
				archs: ['Hexo', '服务器'],
				date: '2024-12-09',
				comment: '朽丘秋雨的个人博客。站长近期心情愉悦，分享生活中的美好瞬间。文章风格一定会和喜欢的人在夏日夜晚牵手慢步。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'FrWalker',
				sitenick: '',
				title: 'FrWalker',
				desc: '听风雨，问星辰，随心归✨',
				link: 'https://blog.frwalker.top/',
				feed: 'https://blog.frwalker.top/atom.xml',
				icon: 'https://image.lolimi.cn/2025/07/22/687f0ffd971b9.ico',
				avatar: 'https://image.lolimi.cn/2025/07/22/687f0ffd971b9.ico',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: 'FrWalker的个人博客。站长热爱生活，分享所见所闻与内心感悟。文章风格听风雨，问星辰，随心归✨。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '陆小启Kairo',
				sitenick: '',
				title: '陆小启Kairo',
				desc: '往者不谏，来者可追',
				link: 'https://blog.zonox.top/',
				feed: 'https://blog.zonox.top/feed/',
				icon: 'https://bu.dusays.com/2025/03/14/67d3fbedaa1c6.webp',
				avatar: 'https://bu.dusays.com/2025/03/14/67d3fbedaa1c6.webp',
				archs: ['Typecho', 'Cloudflare'],
				date: '2024-12-09',
				comment: '陆小启Kairo的个人博客。站长积极向上，记录成长与进步的点滴。文章风格往者不谏，来者可追。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '葱苓小筑',
				sitenick: '',
				title: '葱苓小筑',
				desc: 'Don\'t worry, be happy.',
				link: 'https://blog.ciraos.top/',
				feed: 'https://blog.ciraos.top/feed',
				icon: 'https://blog.ciraos.top/api/f/RgeK/avatar1.avif',
				avatar: 'https://blog.ciraos.top/api/f/RgeK/avatar1.avif',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-12-09',
				comment: '葱苓小筑的个人博客。站长坚持更新，分享个人思考与生活点滴。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'Imz',
				sitenick: '',
				title: 'Imz',
				desc: '仰望星空，脚踏实地。',
				link: 'https://blog.imz.me/',
				feed: '',
				icon: 'https://pic.wudu.ltd/pic/2025/10/04/68e12d685b3a5.webp',
				avatar: 'https://pic.wudu.ltd/pic/2025/10/04/68e12d685b3a5.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: 'Imz的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格仰望星空，脚踏实地。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '唐志远',
				sitenick: '',
				title: '唐志远',
				desc: '立志成为一名架构师',
				link: 'https://fe32.top/',
				feed: 'https://fe32.top/atom.xml',
				icon: 'https://bu.dusays.com/2022/05/02/626f92e193879.jpg',
				avatar: 'https://bu.dusays.com/2022/05/02/626f92e193879.jpg',
				archs: ['Hexo', '服务器'],
				date: '2024-12-09',
				comment: '唐志远的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格立志成为一名架构师。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'MortalCat',
				sitenick: 'Mo的记事簿',
				title: 'Mo的记事簿',
				desc: '万年鸽王，哈哈OvO',
				link: 'https://blog.xiowo.net/',
				feed: 'https://blog.xiowo.net/atom.xml',
				icon: 'https://image.lolimi.cn/2025/07/22/687f0bd346429.png',
				avatar: 'https://image.lolimi.cn/2025/07/22/687f0bd346429.png',
				archs: ['Hexo', 'Netlify'],
				date: '2024-12-09',
				comment: 'Mo的记事簿的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格万年鸽王，哈哈OvO。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '壹人小站',
				sitenick: '',
				title: '壹人小站',
				desc: 'Trust the process.',
				link: 'https://www.xscnet.cn/',
				feed: 'https://www.xscnet.cn/atom.xml',
				icon: 'https://www.xscnet.cn/avatar1.jpg',
				avatar: 'https://www.xscnet.cn/avatar1.jpg',
				archs: ['Vue', 'EdgeOne'],
				date: '2024-12-09',
				comment: '壹人小站的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格Trust the process.。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'fishcpy',
				sitenick: '',
				title: '𝙛𝙞𝙨𝙝𝙘𝙥𝙮',
				desc: '非淡泊无以明志，非宁静无以致远',
				link: 'https://blog.fis.ink/',
				feed: 'https://blog.fis.ink/atom.xml',
				icon: 'https://www.fis.ink/img/logo.png',
				avatar: 'https://www.fis.ink/img/logo.png',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2024-12-09',
				comment: '𝙛𝙞𝙨𝙝𝙘𝙥𝙮的个人博客。站长当前心境平和，专注于个人表达与创作。文章风格非淡泊无以明志，非宁静无以致远\r\n。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'AcoFork',
				sitenick: '',
				title: 'AcoFork',
				desc: 'Protect What You Love!',
				link: 'https://acofork.com/',
				feed: 'https://acofork.com/rss.xml',
				icon: 'https://q2.qlogo.cn/headimg_dl?dst_uin=2726730791&spec=5',
				avatar: 'https://q2.qlogo.cn/headimg_dl?dst_uin=2726730791&spec=5',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'AcoFork的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格Protect What Yo...。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '张洪Heo',
				sitenick: '',
				title: '张洪Heo',
				desc: '分享设计与科技生活',
				link: 'https://blog.zhheo.com/',
				feed: 'https://blog.zhheo.com/atom.xml',
				icon: 'https://image.lolimi.cn/2025/07/22/687f0d0ee6fd3.png',
				avatar: 'https://image.lolimi.cn/2025/07/22/687f0d0ee6fd3.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '张洪Heo的生活随笔博客。站长坚持更新，分享个人思考与生活点滴。文章风格分享设计与科技生活。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '夜轻Blog',
				sitenick: '',
				title: '夜轻Blog',
				desc: '一个人',
				link: 'https://blog.yeqing.net/',
				feed: 'https://blog.yeqing.net/atom.xml',
				icon: 'https://list.yeqing.net/d/oss/image/i/2025/05/15/62868e67dff91285992985db0cce57d5.webp',
				avatar: 'https://list.yeqing.net/d/oss/image/i/2025/05/15/62868e67dff91285992985db0cce57d5.webp',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-12-09',
				comment: '夜轻Blog的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格一个人。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '❖星港◎Star☆',
				sitenick: '',
				title: '❖星港◎Star☆',
				desc: '以博客记录生活与热爱！',
				link: 'https://blog.starsharbor.com/',
				feed: 'https://blog.starsharbor.com/atom.xml',
				icon: 'https://q.qlogo.cn/g?b=qq&nk=288313&s=640',
				avatar: 'https://q.qlogo.cn/g?b=qq&nk=288313&s=640',
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-12-09',
				comment: '❖星港◎Star☆的生活随笔博客。站长坚持更新，分享个人思考与生活点滴。文章风格以博客记录生活与热爱！。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'Xuan\'s blog',
				sitenick: '',
				title: 'Xuan\'s blog',
				desc: '深夜码字时，总为你留一盏暖灯',
				link: 'https://blog.ybyq.wang/',
				feed: 'https://blog.ybyq.wang/feed/',
				icon: 'https://blog.ybyq.wang/usr/themes/handsome/assets/img/avatar.png',
				avatar: 'https://blog.ybyq.wang/usr/themes/handsome/assets/img/avatar.png',
				archs: ['Typecho', '国内 CDN'],
				date: '2024-12-09',
				comment: 'Xuan\'s blog的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格深夜码字时，总为你留一盏暖灯。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '秘柯絮语',
				sitenick: '',
				title: '秘柯絮语',
				desc: 'My Inner Opinion Collection',
				link: 'https://www.mioc.cn/',
				feed: 'https://www.mioc.cn/rss.xml',
				icon: 'https://www.mioc.cn/upload/mioc.svg',
				avatar: 'https://www.mioc.cn/upload/mioc.svg',
				archs: ['Halo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '秘柯絮语的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格My Inner Opinio...。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '百里博客',
				sitenick: '',
				title: '百里博客',
				desc: '一个高中生的博客',
				link: 'https://blog.my0811.cn/',
				feed: 'https://blog.my0811.cn/rss.xml',
				icon: 'https://blog.my0811.cn/favicon.ico',
				avatar: 'https://blog.my0811.cn/favicon.ico',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-12-09',
				comment: '百里博客的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格一个高中生的博客。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'AirTouch',
				sitenick: '',
				title: 'AirTouch',
				desc: '岩间琉璃云间月',
				link: 'https://xsl.im/',
				feed: 'https://www.xsl.im/atom.xml',
				icon: 'https://www.xsl.im/avatar.webp',
				avatar: 'https://www.xsl.im/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: 'AirTouch的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格岩间琉璃云间月。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '叶泯希',
				sitenick: '',
				title: '叶泯希',
				desc: '意义是自己赐予的',
				link: 'https://blog.418121.xyz/',
				feed: 'https://blog.418121.xyz/rss2.xml',
				icon: 'https://blog.418121.xyz/images/avatar.webp',
				avatar: 'https://blog.418121.xyz/images/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '叶泯希的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格意义是自己赐予的。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '小亮的部落阁',
				sitenick: '',
				title: '小亮的部落阁',
				desc: '欲望以提升热忱，毅力以磨平高山',
				link: 'https://blog.752132.xyz/',
				feed: 'https://blog.752132.xyz/atom.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6e1799c43.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6e1799c43.png',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '小亮的部落阁的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格欲望以提升热忱，毅力以磨平高山。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '韩小韩博客',
				sitenick: '',
				title: '韩小韩博客',
				desc: '运气是计划之外的东西.',
				link: 'https://www.vvhan.com/',
				feed: 'https://www.vvhan.com/rss.xml',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=1655466387&s=640',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=1655466387&s=640',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-12-09',
				comment: '韩小韩博客的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格运气是计划之外的东西.。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '东方月初',
				sitenick: '',
				title: '东方月初',
				desc: '分享有趣但又无聊的东西。',
				link: 'https://blog.biuxin.com/',
				feed: 'https://blog.biuxin.com/atom.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6de94d5c3.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6de94d5c3.png',
				archs: ['Golang', '服务器'],
				date: '2024-12-09',
				comment: '东方月初的学习分享博客。站长坚持更新，分享个人思考与生活点滴。文章风格分享有趣但又无聊的东西。。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '胜天半子',
				sitenick: '',
				title: '胜天半子',
				desc: '事已至此，先吃饭吧😋',
				link: 'https://blog.291055.xyz/',
				feed: '',
				icon: 'https://i1.wp.com/ruom.wuaze.com/i/2024/11/02/166823.webp',
				avatar: 'https://i1.wp.com/ruom.wuaze.com/i/2024/11/02/166823.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '胜天半子的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格事已至此，先吃饭吧😋。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'Eilo',
				sitenick: '',
				title: 'Eilo',
				desc: '等等我记一下',
				link: 'https://aptu.net/',
				feed: 'https://aptu.net/rss.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6dc76e073.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6dc76e073.png',
				archs: ['HTML', 'Netlify'],
				date: '2024-12-09',
				comment: 'Eilo的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格等等我记一下。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '新锐博客',
				sitenick: '',
				title: '新锐博客',
				desc: '记录学习与分享资源',
				link: 'https://www.xrbk.cn/',
				feed: 'https://www.xrbk.cn/atom.xml',
				icon: 'https://www.xrbk.cn/favicon.png',
				avatar: 'https://www.xrbk.cn/favicon.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '新锐博客的学习分享博客。站长坚持更新，分享个人思考与生活点滴。文章风格记录学习与分享资源。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '星辰の笔记',
				sitenick: '',
				title: '星辰の笔记',
				desc: '代码 |思考 |分享 | 重复',
				link: 'https://blog.strarry.top/',
				feed: 'https://blog.strarry.top/feed',
				icon: 'https://blog.strarry.top/avatar.jpg',
				avatar: 'https://blog.strarry.top/avatar.jpg',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '星辰の笔记的技术博客。站长坚持更新，分享个人思考与生活点滴。文章风格代码 |思考 |分享 | 重复。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '天海博客',
				sitenick: '',
				title: '天海博客',
				desc: '建站经验记录，实用工具推荐，免费资源分享。',
				link: 'https://www.woolyun.com',
				feed: 'https://woolyun.com/feed/',
				icon: 'https://i.p-i.vip/135/20251129-692a6da7aa977.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6da7aa977.png',
				archs: ['Typecho', 'Cloudflare'],
				date: '2024-12-09',
				comment: '天海博客的学习分享博客。站长坚持更新，分享个人思考与生活点滴。文章风格建站经验记录，实用工具推荐，免...。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'AYaka',
				sitenick: '',
				title: 'AYaka',
				desc: '保护你所爱！❤',
				link: 'https://blog.ayaka0.top/',
				feed: 'https://blog.ayaka0.top/rss.xml',
				icon: 'https://pic.wudu.ltd/pic/2025/08/23/68a92f8655ba4.webp',
				avatar: 'https://pic.wudu.ltd/pic/2025/08/23/68a92f8655ba4.webp',
				archs: ['Astro', 'Cloudflare'],
				date: '2024-12-09',
				comment: 'AYaka的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格保护你所爱！❤。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'Noah',
				sitenick: '',
				title: 'Noah',
				desc: '努力去发光，而不是被照亮',
				link: 'https://blog.noah0932.top/',
				feed: 'https://blog.noah0932.top/rss.xml',
				icon: 'https://cdn.tulan.cyou/noah/2025/07/26/b_5255bd8e31082e2a4332c4eb4172686e.jpg',
				avatar: 'https://cdn.tulan.cyou/noah/2025/07/26/b_5255bd8e31082e2a4332c4eb4172686e.jpg',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-12-09',
				comment: 'Noah的个人博客。站长积极向上，记录成长与进步的点滴。文章风格努力去发光，而不是被照亮。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '策柯',
				sitenick: '',
				title: '策柯',
				desc: '时矫首而遐观',
				link: 'https://blog.xomoe.cn/',
				feed: 'https://blog.xomoe.cn/rss.xml',
				icon: 'https://blog.xomoe.cn/_astro/touxiang.DuQ7TJxD_ZbtHS7.webp',
				avatar: 'https://blog.xomoe.cn/_astro/touxiang.DuQ7TJxD_ZbtHS7.webp',
				archs: ['Astro', '国内 CDN'],
				date: '2024-12-09',
				comment: '策柯的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格时矫首而遐观。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '青桔气球',
				sitenick: '',
				title: '青桔气球',
				desc: '分享网络安全与科技生活',
				link: 'https://blog.qjqq.cn/',
				feed: 'https://blog.qjqq.cn/atom.xml',
				icon: 'https://q2.qlogo.cn/headimg_dl?dst_uin=1645253&spec=640',
				avatar: 'https://q2.qlogo.cn/headimg_dl?dst_uin=1645253&spec=640',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-12-09',
				comment: '青桔气球的技术博客。站长坚持更新，分享个人思考与生活点滴。文章风格分享网络安全与科技生活。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '别碰我的镜头盖',
				sitenick: '',
				title: '别碰我的镜头盖',
				desc: 'AI悦创·创造不同！',
				link: 'https://blog.bornforthis.cn/',
				feed: 'https://blog.bornforthis.cn/atom.xml',
				icon: 'https://weavatar.com/avatar/d2262986371318821a2cfe4dc37a18bd62af3e7e5d531301c87f6066a483faa0?d=letter&letter=A',
				avatar: 'https://weavatar.com/avatar/d2262986371318821a2cfe4dc37a18bd62af3e7e5d531301c87f6066a483faa0?d=letter&letter=A',
				archs: ['Hexo', '服务器'],
				date: '2024-12-09',
				comment: '别碰我的镜头盖的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格AI悦创·创造不同！。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '易航',
				sitenick: '',
				title: '易航',
				desc: '一名编程爱好者的博客，记录与分享编程、学习中的知识点',
				link: 'https://blog.yihang.info/',
				feed: 'https://blog.yihang.info/feed/',
				icon: 'https://blog.yihang.info/favicon.ico',
				avatar: 'https://blog.yihang.info/favicon.ico',
				archs: ['Typecho', '服务器'],
				date: '2024-12-09',
				comment: '易航的技术博客。站长坚持更新，分享个人思考与生活点滴。文章风格一名编程爱好者的博客，记录与分...。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '小米里的大麦',
				sitenick: '',
				title: '小米里的大麦',
				desc: '芝兰生于深谷，不以无人而不芳。',
				link: 'https://www.minbit.top/',
				feed: 'https://www.minbit.top/atom.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6d093173d.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6d093173d.png',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '小米里的大麦的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格芝兰生于深谷，不以无人而不芳。。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'Evilrabbit',
				sitenick: '',
				title: 'Evilrabbit',
				desc: '爱 Coding 爱生活',
				link: 'https://blog.yujiay.wang/',
				feed: 'https://blog.yujiay.wang/atom.xml',
				icon: 'https://blog.yujiay.wang/images/site/BlogHsvg.png',
				avatar: 'https://blog.yujiay.wang/images/site/BlogHsvg.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'Evilrabbit的生活随笔博客。站长坚持更新，分享个人思考与生活点滴。文章风格爱 Coding 爱生活。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'lololowe',
				sitenick: '',
				title: 'lololowe',
				desc: '计网，网安知识分享',
				link: 'https://blog.lololowe.com/',
				feed: 'https://blog.lololowe.com/atom.xml',
				icon: 'https://blog.lololowe.com/favicon.ico',
				avatar: 'https://blog.lololowe.com/favicon.ico',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'lololowe的学习分享博客。站长坚持更新，分享个人思考与生活点滴。文章风格计网，网安知识分享。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '静观小窗',
				sitenick: '',
				title: '静观小窗',
				desc: '窗外是蓝天白云，心里是小杏扉间。',
				link: 'https://www.vindo.cn/',
				feed: 'https://www.vindo.cn/feed.xml',
				icon: 'https://img.vindo.cn/AVATOR.png',
				avatar: 'https://img.vindo.cn/AVATOR.png',
				archs: ['Vue', 'EdgeOne'],
				date: '2024-12-09',
				comment: '静观小窗的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格窗外是蓝天白云，心里是小杏扉间。。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'bbb-lsy07',
				sitenick: '',
				title: 'bbb-lsy07',
				desc: '科技激荡人文，洞见智慧本真。',
				link: 'https://blog.6uu.us/',
				feed: 'https://blog.6uu.us/rss.xml',
				icon: 'https://blog.6uu.us/upload/00000.png',
				avatar: 'https://blog.6uu.us/upload/00000.png',
				archs: ['Halo', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'bbb-lsy07的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格科技激荡人文，洞见智慧本真。。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '周润发',
				sitenick: '',
				title: '周润发',
				desc: '收录开源，好用的互联网项目',
				link: 'https://blog.zrf.me/',
				feed: 'https://blog.zrf.me/atom.xml',
				icon: 'https://image.lolimi.cn/2025/10/07/68e472302fe55.png',
				avatar: 'https://image.lolimi.cn/2025/10/07/68e472302fe55.png',
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-12-09',
				comment: '周润发的技术博客。站长坚持更新，分享个人思考与生活点滴。文章风格收录开源，好用的互联网项目。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '拥抱日出的小屋',
				sitenick: '',
				title: '拥抱日出的小屋',
				desc: '拥抱日出，也拥抱生活',
				link: 'https://blog.ybrc.top/',
				feed: 'https://blog.ybrc.top/feed.xml',
				icon: 'https://blog.ybrc.top/upload/logo.jpg',
				avatar: 'https://blog.ybrc.top/upload/logo.jpg',
				archs: ['Halo', '服务器'],
				date: '2024-12-09',
				comment: '拥抱日出的小屋的生活随笔博客。站长坚持更新，分享个人思考与生活点滴。文章风格拥抱日出，也拥抱生活。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '凌尘',
				sitenick: '',
				title: '凌尘',
				desc: '于高山之巅，方见大河奔涌；于群峰之上，更觉长风浩荡。',
				link: 'https://b.icxk.cn/',
				feed: '',
				icon: 'https://i.p-i.vip/135/20251129-692a6c95625e8.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6c95625e8.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '凌尘的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格于高山之巅，方见大河奔涌；于群...。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'snows_l',
				sitenick: '',
				title: 'snows_l',
				desc: '小得盈满！',
				link: 'http://snows-l.site/',
				feed: '',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=37523953&s=640',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=37523953&s=640',
				archs: ['PHP', '服务器'],
				date: '2024-12-09',
				comment: 'snows_l的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格小得盈满！。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '梨尽兴',
				sitenick: '',
				title: '梨尽兴',
				desc: 'A place for peace',
				link: 'https://blog.ljx.icu/',
				feed: 'https://blog.ljx.icu/rss.xml',
				icon: 'https://blog.ljx.icu/favicon.png',
				avatar: 'https://blog.ljx.icu/favicon.png',
				archs: ['Astro', '国内 CDN'],
				date: '2024-12-09',
				comment: '梨尽兴的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格A place for peace。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'JustPureH20',
				sitenick: '',
				title: 'JustPureH2O',
				desc: '穷方圆平直之情，尽规矩准绳之用',
				link: 'https://justpureh2o.cn/',
				feed: '',
				icon: 'https://pic.wudu.ltd/pic/2025/12/12/693bfade6a038.jpg',
				avatar: 'https://pic.wudu.ltd/pic/2025/12/12/693bfade6a038.jpg',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: 'JustPureH2O的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格穷方圆平直之情，尽规矩准绳之用。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '酥米的小站',
				sitenick: '',
				title: '酥米的小站',
				desc: '终有一日，寻梦中人',
				link: 'https://www.sumi233.top/',
				feed: 'https://www.sumi233.top/atom.xml',
				icon: 'https://scdn.us.kg/gh/huang233893/blog-image-bed@main/top/huang233893/imgs/blog/usersumi.png',
				avatar: 'https://scdn.us.kg/gh/huang233893/blog-image-bed@main/top/huang233893/imgs/blog/usersumi.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '酥米的小站的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格终有一日，寻梦中人。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '安知鱼',
				sitenick: '',
				title: '安知鱼',
				desc: '生活明朗，万物可爱',
				link: 'https://blog.anheyu.com/',
				feed: 'https://blog.anheyu.com/atom.xml',
				icon: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				avatar: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				archs: ['Golang', 'EdgeOne'],
				date: '2024-12-09',
				comment: '安知鱼的生活随笔博客。站长坚持更新，分享个人思考与生活点滴。文章风格生活明朗，万物可爱。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'Liushen',
				sitenick: '清羽飞扬',
				title: '清羽飞扬',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: 'https://blog.liushen.fun/favicon.ico',
				avatar: 'https://q.qlogo.cn/g?b=qq&nk=3162475700&s=640',
				archs: ['Hexo', 'EdgeOne'],
				date: '2025-01-01',
				comment: '近期在成都活动、学 C++，曾感冒。文章多涉 Hexo/Butterfly 主题魔改、Anheyu-App 部署、TinyAuth 认证等筑站运维内容，也有旅游、观影类闲情杂记。',
			},
		],
	},
	// #endregion
] satisfies FeedGroup[]
