// 友链检测 CLI 需要使用显式导入和相对路径
import type { FeedGroup } from '../app/types/feed'

export default [
	// #region Clarity
	{
		name: '『膜拜大佬』',
		desc: '技术实力强、影响力大的博主，值得学习膜拜',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '安知鱼',
				sitenick: '',
				title: '安知鱼',
				desc: '生活明朗，万物可爱',
				link: 'https://blog.anheyu.com/',
				feed: 'https://blog.anheyu.com/atom.xml',
				icon: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				avatar: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				archs: ['Golang', 'EdgeOne'],
				date: '2024-12-09',
				comment: '安和鱼的博客（2025年底持续更新），聚焦前端技术与Anheyu-App相关，分享CSS新方案、React漏洞、CSRF攻击等技术解析，及应用安装迁移教程，也含Mac使用体验、武汉旅游日志与年度总结，技术实用且兼顾生活气息。',
			},
			{
				author: '张洪Heo',
				sitenick: '',
				title: '张洪Heo',
				desc: '分享设计与科技生活',
				link: 'https://blog.zhheo.com/',
				feed: 'https://blog.zhheo.com/atom.xml',
				icon: 'https://image.lolimi.cn/2025/07/22/687f0d0ee6fd3.png',
				avatar: 'https://image.lolimi.cn/2025/07/22/687f0d0ee6fd3.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '张洪Heo的博客（2026年更新），聚焦设计与科技生活。内容含Mac/iOS软件推荐、iPhone17上手体验、Final Cut Pro剪辑技巧、智能家居接入等实用经验，也有闲聊杂谈与年度博主推荐，兼具数码干货与生活气息。',
			},
			{
				author: '纸鹿',
				sitenick: '摸鱼处',
				title: '纸鹿摸鱼处',
				desc: '纸鹿至麓不知路，支炉制露不止漉',
				link: 'https://blog.zhilu.site/',
				feed: 'https://blog.zhilu.site/atom.xml',
				icon: 'https://weavatar.com/avatar/47c0f2e82b76d9b10eb3023df9e02e4e3fdbeaf5b74b842063f207971e7fbe7b?s=160',
				avatar: 'https://weavatar.com/avatar/47c0f2e82b76d9b10eb3023df9e02e4e3fdbeaf5b74b842063f207971e7fbe7b?s=160',
				archs: ['Nuxt', 'Vercel'],
				date: '2024-12-09',
				comment: '纸鹿摸鱼处博客，聚焦前端开发、系统配置与数码体验，分享VitePress优化、深浅色模式等技术指南，及ArchLinux安装、数码“捡垃圾”心得，也有生活杂谈与避坑经验，实用又有温度。',
			},
			{
				author: '周润发',
				sitenick: '',
				title: '周润发',
				desc: '收录开源，好用的互联网项目',
				link: 'https://blog.zrf.me/',
				feed: 'https://blog.zrf.me/atom.xml',
				icon: 'https://image.lolimi.cn/2025/10/07/68e472302fe55.png',
				avatar: 'https://image.lolimi.cn/2025/10/07/68e472302fe55.png',
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-12-09',
				comment: '周润发博客是技术极客与生活观察者的跨界空间，聚焦开源工具与互联网实用项目分享。近期深度测评Cloudflare边缘证书部署、Vercel加速优化等硬核技术，揭秘临时邮箱搭建、订阅链接聚合等开发者刚需，并记录换电池翻车、域名抢注等趣味日常。内容横跨网络安全、系统调优、AI应用等领域，风格务实接地气，通过代码片段与实操指南降低技术门槛，同时以幽默笔触消解工具理性，是极客圈的宝藏工具库与治愈系精神角落。',
			},

		],
	},
	{
		name: '『相谈甚多』',
		desc: '经常互动、关系密切的博主',
		entries: [
			{
				author: 'klcdm',
				sitenick: '朽丘秋雨',
				title: '朽丘秋雨',
				desc: '一定会和喜欢的人在夏日夜晚牵手慢步',
				link: 'https://koxiuqiu.cn/',
				feed: 'https://koxiuqiu.cn/atom.xml',
				icon: 'https://koxiuqiu.cn/img/avatar/avatar.png',
				avatar: 'https://koxiuqiu.cn/img/avatar/xiaokeb.png',
				archs: ['Hexo', '服务器'],
				date: '2024-12-09',
				comment: '小柯的朽丘秋雨（2025年底修整新主题），近期调整个人状态后将恢复季更。内容以生活日志、月度/年度总结为主，谈及亲情、代际观念等感悟，也有情感杂语与暂别絮语，满含个人真实思绪与生活烟火气。',
			},
			{
				author: '𝙛𝙞𝙨𝙝𝙘𝙥𝙮',
				sitenick: '',
				title: '𝙛𝙞𝙨𝙝𝙘𝙥𝙮',
				desc: '人生漫长，不妨多解锁些鲜活体验',
				link: 'https://blog.fis.ink/',
				feed: 'https://blog.fis.ink/atom.xml',
				icon: 'https://file.fis.ink/img/fishcpy/logo.png',
				avatar: 'https://file.fis.ink/img/fishcpy/logo.png',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'fishcpy的小破站，2025年5月曾遭遇服务器攻击并处理CDN相关问题。内容涵盖运维部署（1panel搭建备案系统、哪吒监控美化）、设备体验、问题排查，也有音乐播放器分享、爱国图片合集等，实用与情怀兼具。',
			},
			{
				author: 'Liushen',
				sitenick: '清羽飞扬',
				title: '清羽飞扬',
				desc: '柳影曳曳，清酒孤灯，扬笔撒墨，心境如霜',
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: 'https://blog.liushen.fun/favicon.ico',
				avatar: 'https://q.qlogo.cn/g?b=qq&nk=3162475700&s=640',
				archs: ['Hexo', 'EdgeOne'],
				date: '2025-01-01',
				comment: '近期在成都活动、学 C++，曾感冒。文章多涉 Hexo/Butterfly 主题魔改、Anheyu-App 部署、TinyAuth 认证等筑站运维内容，也有旅游、观影类闲情杂记。',
			},
			{
				author: 'Xuan\'s blog',
				sitenick: '',
				title: 'Xuan\'s blog',
				desc: '分享技术教程和学习笔记',
				link: 'https://blog.ybyq.wang/',
				feed: 'https://blog.ybyq.wang/feed/',
				icon: 'https://blog.ybyq.wang/usr/themes/handsome/assets/img/avatar.png',
				avatar: 'https://blog.ybyq.wang/usr/themes/handsome/assets/img/avatar.png',
				archs: ['Typecho', '国内 CDN'],
				date: '2024-12-09',
				comment: 'Xuan\'s blog（2025年11月更新），站长获项目劳务费，记录晚霞、中秋游记等生活点滴。内容涵盖Umami升级、Typecho博客运维（主题美化、插件监控等）教程，及GPT聊天应用、健身房管理系统开发实践，兼具技术干货与生活随笔。',
			},
		],
	},
	// #endregion
	// #region 网上邻居
	{
		name: '『网上邻居』',
		desc: '哔——啵——电波通讯中，欢迎常来串门',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '梦爱吃鱼',
				sitenick: '',
				title: '梦爱吃鱼',
				desc: '但愿日子清静抬头遇见的满是柔情',
				link: 'https://blog.bsgun.cn/',
				feed: 'https://blog.bsgun.cn/atom.xml',
				icon: 'https://lib.bsgun.cn/Hexo-static/img/favicon.ico',
				avatar: 'https://image.lolimi.cn/2026/02/08/6987f2f6639f3.webp',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2024-12-09',
				comment: '梦爱吃鱼的博客（2025年仍有更新），聚焦Hexo博客主题魔改，分享首页样式优化、侧边栏组件添加（评论、倒计时等）、宠物挂件等教程，也含开源项目盘点与工具部署方案，专注博客美化与功能拓展。',
			},
			{
				author: 'FrWalker',
				sitenick: '',
				title: 'FrWalker',
				desc: '听风雨，问星辰，随心归✨',
				link: 'https://blog.frwalker.top/',
				feed: 'https://blog.frwalker.top/atom.xml',
				icon: 'https://image.lolimi.cn/2025/07/22/687f0ffd971b9.ico',
				avatar: 'https://image.lolimi.cn/2025/07/22/687f0ffd971b9.ico',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '站长近期专注创作，博客以Linux技术与开源项目为核心。有Linux系统安装、配置教程，也分享开源项目实践经验。致力于为Linux爱好者与开发者提供专业知识，助力在开源世界探索前行。 ',
			},
			{
				author: '葱苓sama',
				sitenick: '葱苓小筑',
				title: '葱苓小筑',
				desc: '风带来了故事的种子，时间使其发芽。',
				link: 'https://blog.ciraos.top/',
				feed: 'https://blog.ciraos.top/atom.xml',
				icon: 'https://i.p-i.vip/135/20260102-6957b41708b60.png',
				avatar: 'https://i.p-i.vip/135/20260102-6957b41708b60.png',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-12-09',
				comment: '该博客站长当下专注创作，文章多为软件资源分享及使用教程，像各类实用工具、办公软件等。也涵盖电脑系统优化技巧，聚焦数码软件领域，为用户提供便捷高效的使用指南与资源。 ',
			},
			{
				author: 'Imz',
				sitenick: '',
				title: 'Imz',
				desc: '仰望星空，脚踏实地。',
				link: 'https://blog.imz.me/',
				feed: '',
				icon: 'https://pic.wudu.ltd/pic/2025/10/04/68e12d685b3a5.webp',
				avatar: 'https://pic.wudu.ltd/pic/2025/10/04/68e12d685b3a5.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: 'imz的小站（2025年10月更新标语），聚焦多技术领域，分享Chrome多开、视频下载等软件使用教程，及Alist-Helper问题解决、Hexo插件配置等内容，涉及JS、Docker、Vue等技术，兼具实用技巧与技术实践。',
			},
			{
				author: '唐志远',
				sitenick: '',
				title: '唐志远',
				desc: '立志成为一名架构师',
				link: 'https://fe32.top/',
				feed: 'https://fe32.top/atom.xml',
				icon: 'https://bu.dusays.com/2022/05/02/626f92e193879.jpg',
				avatar: 'https://bu.dusays.com/2022/05/02/626f92e193879.jpg',
				archs: ['Hexo', '服务器'],
				date: '2024-12-09',
				comment: '唐志远的博客（fe32.top），聚焦前端技术与服务器搭建。内容涵盖Hexo+Butterfly博客搭建、HTTP协议、CSS规范与动画库推荐、Vue3问题解决等前端干货，也有CentOS安装、VMware配置等服务器教程，实用技巧丰富，技术导向明确。',
			},
			{
				author: 'Mo的记事簿',
				sitenick: '',
				title: 'Mo的记事簿',
				desc: '万年鸽王，哈哈OvO',
				link: 'https://blog.xiowo.net/',
				feed: 'https://blog.xiowo.net/atom.xml',
				icon: 'https://image.lolimi.cn/2025/07/22/687f0bd346429.png',
				avatar: 'https://image.lolimi.cn/2025/07/22/687f0bd346429.png',
				archs: ['Hexo', 'Netlify'],
				date: '2024-12-09',
				comment: 'MortalCat的博客（2025年持续更新），聚焦Hexo博客搭建与美化，分享安知鱼主题配置、Twikoo评论优化等教程，也涵盖Emby代理、Android网络修复、GitHub加速等工具使用技巧，兼具技术笔记与实用指南，干货满满。',
			},
			{
				author: '壹人小站',
				sitenick: '',
				title: '壹人小站',
				desc: 'Trust the process.',
				link: 'https://www.xscnet.cn/',
				feed: 'https://www.xscnet.cn/atom.xml',
				icon: 'https://img.xscnet.cn//i/2025/07/09/686e64ec429db.png',
				avatar: 'https://img.xscnet.cn//i/2025/07/09/686e64ec429db.png',
				archs: ['Vue', 'EdgeOne'],
				date: '2024-12-09',
				comment: '站长为高三学生，将在2026年6月高考后回归。内容含站点CDN优化、数码推荐、音乐分享、日常小结，还开发过游戏存档同步工具，兼具建站技术、生活点滴与兴趣分享。',
			},
			{
				author: 'AcoFork',
				sitenick: '',
				title: 'AcoFork',
				desc: 'Protect What You Love!',
				link: 'https://blog.acofork.com/',
				feed: 'https://blog.acofork.com/rss.xml',
				icon: 'https://q2.qlogo.cn/headimg_dl?dst_uin=2726730791&spec=5',
				avatar: 'https://q2.qlogo.cn/headimg_dl?dst_uin=2726730791&spec=5',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-12-09',
				comment: '二叉树树的博客（2025年底更新），近期站点遭大规模DDoS攻击。内容聚焦Serverless、云函数等技术，分享Umami部署、匿名文件上载器搭建、远程控机等教程，也涉及米哈游AI逆改与QQBot开发，技术实用且聚焦高效部署。',
			},
			{
				author: '夜轻Blog',
				sitenick: '',
				title: '夜轻Blog',
				desc: '一个人',
				link: 'https://blog.yeqing.net/',
				feed: 'https://blog.yeqing.net/atom.xml',
				icon: 'https://list.yeqing.net/d/oss/image/i/2025/05/15/62868e67dff91285992985db0cce57d5.webp',
				avatar: 'https://list.yeqing.net/d/oss/image/i/2025/05/15/62868e67dff91285992985db0cce57d5.webp',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-12-09',
				comment: '夜轻Blog（2025年更新），站长提及疲惫想停下，启用新域名qzq.im。内容聚焦免费互联网服务、VPS与CDN（零九、橘喵云等）使用体验，也含随机图片API文档制作，主打网络服务测评与实用资源分享。',
			},
			{
				author: '❖星港◎Star☆',
				sitenick: '',
				title: '❖星港◎Star☆',
				desc: '以博客记录生活与热爱！',
				link: 'https://blog.starsharbor.com/',
				feed: 'https://blog.starsharbor.com/atom.xml',
				icon: 'https://q.qlogo.cn/g?b=qq&nk=288313&s=640',
				avatar: 'https://q.qlogo.cn/g?b=qq&nk=288313&s=640',
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-12-09',
				comment: '记录建站多周年历程与上海旅行纪念。内容涵盖HarmonyOS NEXT系统体验、solitude主题配置（字体/友链/数据统计）等技术分享，也有原神版本梳理、饮品测评、华为手表使用记录，兼具技术实践与生活随笔，风格多元。',
			},
			{
				author: '百里博客',
				sitenick: '',
				title: '百里博客',
				desc: '一个高中生的博客',
				link: 'https://blog.my0811.cn/',
				feed: 'https://blog.my0811.cn/rss.xml',
				icon: 'https://blog.my0811.cn/favicon.ico',
				avatar: 'https://blog.my0811.cn/favicon.ico',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-12-09',
				comment: '百里博客（2025年8月更新），专注技术实践与实用教程。内容涵盖Android逆向（喵窝计账破解）、Qwen3-Coder大模型安装、Fuwari博客追番列表接入，及Python步数自动化脚本开发，聚焦逆向工程、AI编程与博客定制，干货实用且落地性强。',
			},
			{
				author: 'AirTouch',
				sitenick: '',
				title: 'AirTouch',
				desc: '岩间琉璃云间月',
				link: 'https://xsl.im/',
				feed: 'https://www.xsl.im/atom.xml',
				icon: 'https://image.lolimi.cn/2026/03/22/69bf488fd02dd.webp',
				avatar: 'https://image.lolimi.cn/2026/03/22/69bf488fd02dd.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: 'AirTouch的博客（2025年11月持续更新），近期更新Stellar主题。内容聚焦技术折腾与项目分享，含Artalk评论区配置、Hexo AI摘要等博客优化教程，Librechat AI部署、临时邮箱搭建等项目推荐，还有VPS测评与系统问题解决方案，技术实用且覆盖多元场景。',
			},
			{
				author: '叶泯希',
				sitenick: '',
				title: '叶泯希',
				desc: '意义是自己赐予的',
				link: 'https://blog.418121.xyz/',
				feed: 'https://blog.418121.xyz/rss2.xml',
				icon: 'https://blog.418121.xyz/images/avatar.webp',
				avatar: 'https://blog.418121.xyz/images/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '叶泯希的博客，内容涵盖Solitude主题魔改、日常随笔与摄影作品，也分享“尊重分歧”“珍惜眼前”的人生感悟。无明确近期特殊近况，聚焦个人生活记录、博客折腾与影像表达，风格细腻贴合生活。',
			},
			{
				author: '小亮的部落阁',
				sitenick: '',
				title: '小亮的部落阁',
				desc: '欲望以提升热忱，毅力以磨平高山',
				link: 'https://blog.752132.xyz/',
				feed: 'https://blog.752132.xyz/atom.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6e1799c43.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6e1799c43.png',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '小亮的部落阁（2025年9月更新），站长部署了个人主页、博客等多个实用项目。内容聚焦Hexo相关，含博客搭建、主题美化、侧边栏添加“历史上的今天”、图床搭建等教程，也记录网站崩溃后重构经验，专注博客折腾与实用技术分享。',
			},
			{
				author: '韩小韩博客',
				sitenick: '',
				title: '韩小韩博客',
				desc: '运气是计划之外的东西.',
				link: 'https://www.vvhan.com/',
				feed: 'https://www.vvhan.com/rss.xml',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=1655466387&s=640',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=1655466387&s=640',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-12-09',
				comment: '韩小韩博客的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格运气是计划之外的东西.。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: '东方月初',
				sitenick: '',
				title: '东方月初',
				desc: '分享有趣但又无聊的东西。',
				link: 'https://blog.biuxin.com/',
				feed: 'https://blog.biuxin.com/atom.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6de94d5c3.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6de94d5c3.png',
				archs: ['Golang', '服务器'],
				date: '2024-12-09',
				comment: 'Biuxin的博客（2025年持续更新），聚焦技术实践与生活随笔。内容含Typecho博客优化、服务器运维等实用技巧，也记录日常感悟与兴趣分享，兼具落地性技术干货与真实生活思绪，风格简约且内容多元。',
			},
			{
				author: '胜天半子',
				sitenick: '',
				title: '胜天半子',
				desc: '事已至此，先吃饭吧😋',
				link: 'https://blog.291055.xyz/',
				feed: '',
				icon: 'https://image.lolimi.cn/2026/03/22/69bf488fb8b40.webp',
				avatar: 'https://image.lolimi.cn/2026/03/22/69bf488fb8b40.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '胜天半子的个人博客。站长坚持更新，分享个人思考与生活点滴。文章风格事已至此，先吃饭吧😋。记录个人成长历程，分享生活感悟与经验，欢迎访问交流。',
			},
			{
				author: 'Eilo',
				sitenick: '',
				title: 'Eilo',
				desc: '等等我记一下',
				link: 'https://aptu.net/',
				feed: 'https://aptu.net/rss.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6dc76e073.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6dc76e073.png',
				archs: ['HTML', 'Netlify'],
				date: '2024-12-09',
				comment: '无特殊近期变动。内容聚焦技术实践与生活随笔，涵盖服务器运维、软件实用技巧等干货，也记录日常感悟与兴趣点滴，兼具技术落地性与生活真实感，风格简洁且内容多元。',
			},
			{
				author: '新锐博客',
				sitenick: '',
				title: '新锐博客',
				desc: '记录学习与分享资源',
				link: 'https://www.xrbk.cn/',
				feed: 'https://www.xrbk.cn/atom.xml',
				icon: 'https://www.xrbk.cn/favicon.png',
				avatar: 'https://www.xrbk.cn/favicon.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '无特殊近期近况。内容涵盖技术实践、生活随笔与兴趣分享，含建站相关技巧、日常感悟等，兼具实用干货与真实生活气息，风格简约质朴，内容多元贴合个人表达。',
			},
			{
				author: '星辰の笔记',
				sitenick: '',
				title: '星辰の笔记',
				desc: '代码 |思考 |分享 | 重复',
				link: 'https://blog.strarry.top/',
				feed: '',
				icon: 'https://blog.strarry.top/avatar.jpg',
				avatar: 'https://blog.strarry.top/avatar.jpg',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '内容涵盖技术实践、生活随笔与兴趣分享，含建站相关技巧、日常感悟等实用干货与个人思绪，风格清新简约，兼具技术落地性与生活气息，内容多元贴合个人表达。',
			},
			{
				author: '天海博客',
				sitenick: '',
				title: '天海博客',
				desc: '建站经验记录，实用工具推荐，免费资源分享。',
				link: 'https://woolyun.com',
				feed: 'https://woolyun.com/feed/',
				icon: 'https://i.p-i.vip/135/20251129-692a6da7aa977.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6da7aa977.png',
				archs: ['Typecho', 'Cloudflare'],
				date: '2024-12-09',
				comment: '天海博客（woolyun.com）由天海牧歌运营，2025年11月持续更新。内容涵盖好物分享（PS2025、迅雷12等）、AI相关、云服务器知识、技术实操及网络安全技巧，实用且多元。',
			},
			{
				author: 'AYaka',
				sitenick: '',
				title: 'AYaka',
				desc: '保护你所爱！❤',
				link: 'https://blog.ayaka0.top/',
				feed: 'https://blog.ayaka0.top/rss.xml',
				icon: 'https://image.lolimi.cn/2026/02/23/699c410d8e03a.webp',
				avatar: 'https://image.lolimi.cn/2026/02/23/699c410d8e03a.webp',
				archs: ['Astro', 'Cloudflare'],
				date: '2024-12-09',
				comment: '由Kamisato Ayaka运营，2025年8月高频更新，欢迎交换友链。内容聚焦技术领域，含Linux、前端、Python、Git、Astro博客搭建等干货，还有排版工具故障修复、AI项目优化等实用分享。',
			},
			{
				author: 'Noah',
				sitenick: '',
				title: 'Noah',
				desc: '努力去发光，而不是被照亮',
				link: 'https://blog.noah0932.top/',
				feed: 'https://blog.noah0932.top/rss.xml',
				icon: 'https://image.lolimi.cn/2026/03/02/69a5464105bd6.png',
				avatar: 'https://image.lolimi.cn/2026/03/02/69a5464105bd6.png',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-12-09',
				comment: 'NoahのBlog（blog.noah0932.top）近期活跃更新，内容多元。涵盖技术干货（Hexo问题解决、CloudFlare部署等）、邮箱/教育邮箱申请、DNS对比，也有日常感悟、明信片温情活动，实用与温情兼具。',
			},
			{
				author: '策柯',
				sitenick: '',
				title: '策柯',
				desc: '时矫首而遐观',
				link: 'https://blog.xomoe.cn/',
				feed: 'https://blog.xomoe.cn/rss.xml',
				icon: 'https://image.lolimi.cn/2026/03/07/69ac18f3cae3a.webp',
				avatar: 'https://image.lolimi.cn/2026/03/07/69ac18f3cae3a.webp',
				archs: ['Astro', '国内 CDN'],
				date: '2024-12-09',
				comment: '2025年8-10月持续更新，聚焦音乐与技术领域。收录华语、日语、二次元等多元曲风歌曲，也分享Linux配置、博客主题优化等技术干货，内容丰富且实用。',
			},
			{
				author: '青桔气球',
				sitenick: '',
				title: '青桔气球',
				desc: '分享网络安全与科技生活',
				link: 'https://blog.qjqq.cn/',
				feed: 'https://blog.qjqq.cn/atom.xml',
				icon: 'https://q2.qlogo.cn/headimg_dl?dst_uin=1645253&spec=640',
				avatar: 'https://q2.qlogo.cn/headimg_dl?dst_uin=1645253&spec=640',
				archs: ['Hexo', '国内 CDN'],
				date: '2024-12-09',
				comment: '青桔气球是专注网络安全与科技生活的个人技术博客，持续分享实战导向的建站教程（如Solitude日历系统、Hexo自动化部署）、轻量化网盘方案（ZFile/Docker部署）、API接口开发（QQ/微信生态）及运维优化经验。博主近期精进于自动化SSL证书推送、边缘计算加速（EdgeOne）等技术探索，页面风格简约实用，致力于通过代码片段与图文结合降低技术落地门槛，是开发者与极客探索低成本解决方案的优质参考源。',
			},
			{
				author: '别碰我的镜头盖',
				sitenick: '',
				title: '别碰我的镜头盖',
				desc: 'AI悦创·创造不同！',
				link: 'https://blog.bornforthis.cn/',
				feed: 'https://blog.bornforthis.cn/atom.xml',
				icon: 'https://weavatar.com/avatar/d2262986371318821a2cfe4dc37a18bd62af3e7e5d531301c87f6066a483faa0?d=letter&letter=A',
				avatar: 'https://weavatar.com/avatar/d2262986371318821a2cfe4dc37a18bd62af3e7e5d531301c87f6066a483faa0?d=letter&letter=A',
				archs: ['Hexo', '服务器'],
				date: '2024-12-09',
				comment: '别碰我的镜头盖是编程导师悦创的个人技术博客，融合代码教学与生活记录。近期专注于Python/C++/算法一对一辅导，分享DeepSeek模型实操、信息奥赛题解及摄影课程，并推出高考志愿填报指南。技术专栏涵盖Hexo魔改、自动化脚本开发（如自动生成文章元数据），生活板块记录育儿日常（百天拍照计划、母婴用品清单）与家庭故事。风格幽默接地气，通过代码案例与实战经验降低学习门槛，同时开辟接单渠道，提供作业代写服务，展现极客与奶爸的双重身份。',
			},
			{
				author: '易航',
				sitenick: '',
				title: '易航',
				desc: '一名编程爱好者的博客，记录与分享编程、学习中的知识点',
				link: 'https://blog.yihang.info/',
				feed: 'https://blog.yihang.info/feed/',
				icon: 'https://blog.yihang.info/favicon.ico',
				avatar: 'https://blog.yihang.info/favicon.ico',
				archs: ['Typecho', '服务器'],
				date: '2024-12-09',
				comment: '易航博客（blog.yihang.info）2025年12月持续更新，聚焦技术领域。分享PHP新版本特性、Web前端优化等教程，提供支付系统、聊天系统等源码资源，还涵盖数码新闻、网络安全工具推荐，实用干货丰富。',
			},
			{
				author: '小米里的大麦',
				sitenick: '',
				title: '小米里的大麦',
				desc: '芝兰生于深谷，不以无人而不芳。',
				link: 'https://www.minbit.top/',
				feed: 'https://www.minbit.top/atom.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6d093173d.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6d093173d.png',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '“小米里的大麦”的博客（www.minbit.top）2025年持续更新，未备案但提供多加速域名。聚焦技术领域，分享C++ STL、Linux、MySQL、算法等干货，也有ChatGPT Go套餐等实用资源，是记录学习与技术分享的平台。',
			},
			{
				author: 'Evilrabbit',
				sitenick: '',
				title: 'Evilrabbit',
				desc: '爱 Coding 爱生活',
				link: 'https://blog.yujiay.wang/',
				feed: 'https://blog.yujiay.wang/atom.xml',
				icon: 'https://blog.yujiay.wang/images/site/BlogHsvg.png',
				avatar: 'https://blog.yujiay.wang/images/site/BlogHsvg.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'Evilrabbit Blog（blog.yujiay.wang）2025年持续更新，内容多元。涵盖技术实践（Hexo灰度发布、主题美化）、硬件折腾、AI与网络安全，也有科技圈动态、生活分享等，兼具技术干货与生活感悟，实用且丰富。',
			},
			{
				author: 'lololowe',
				sitenick: '',
				title: 'lololowe',
				desc: '计网，网安知识分享',
				link: 'https://blog.lololowe.com/',
				feed: 'https://blog.lololowe.com/atom.xml',
				icon: 'https://blog.lololowe.com/favicon.ico',
				avatar: 'https://blog.lololowe.com/favicon.ico',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'lololowe的博客是技术爱好者lololowe的恬淡技术空间，深耕网络安全与网络工程领域。近期聚焦OpenStack快速部署实战、Chrome浏览器性能优化、网络协议解析（MTU/链路检测/BFD）等硬核技术，同时分享环境配置心得与存储技术方案。技术专栏涵盖Python自动化脚本、Docker容器化部署、Linux系统调优等实战内容，风格朴实注重实操，通过代码片段与原理图解降低复杂协议理解门槛，是网络工程师与运维人员的实用工具库。',
			},
			{
				author: '静观小窗',
				sitenick: '',
				title: '静观小窗',
				desc: '窗外是蓝天白云，心里是小杏扉间。',
				link: 'https://www.vindo.cn/',
				feed: 'https://www.vindo.cn/feed.xml',
				icon: 'https://img.vindo.cn/AVATOR.png',
				avatar: 'https://img.vindo.cn/AVATOR.png',
				archs: ['Vue', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'Vindo的个人博客聚焦技术与人文交织的多元领域，展现开发者与历史爱好者的跨界视角。近期文章涵盖《构建网络友邻对抗信息茧房》的Web生态思考、《BlogsClub中文博客联盟》的社区实践观察，以及《文化隐喻如何塑造认知》的深度书评，并分享了《一键自动化图片压缩工具》等技术干货。作为细节控与复古情怀持有者（痴迷南宋美学与Archer设计哲学），持续探索平面设计创新与独立博客的共生可能，致力于在AI浪潮中守护内容温度。',
			},
			{
				author: 'bbb-lsy07',
				sitenick: '',
				title: 'bbb-lsy07',
				desc: '科技激荡人文，洞见智慧本真。',
				link: 'https://blog.tsoo.net/',
				feed: 'https://blog.tsoo.net/rss.xml',
				icon: 'https://image.lolimi.cn/2026/02/23/699c41923dea8.webp',
				avatar: 'https://image.lolimi.cn/2026/02/23/699c41923dea8.webp',
				archs: ['Halo', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'bbb-lsy07的博客2025年11月持续更新，聚焦实用技术。分享服务器搭建、博客部署、邮箱/网盘搭建等教程，含服务器测评、AI相关内容，也有研学记录等生活分享，干货满满且易上手。',
			},
			{
				author: '凌尘',
				sitenick: '',
				title: '凌尘',
				desc: '于高山之巅，方见大河奔涌；于群峰之上，更觉长风浩荡。',
				link: 'https://b.icxk.cn/',
				feed: '',
				icon: 'https://i.p-i.vip/135/20251129-692a6c95625e8.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6c95625e8.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '凌尘k的博客2024-2025年持续更新，聚焦技术开发与日常分享。技术上涵盖CSS特效、Hexo魔改、服务器搭建（Minecraft、静态网站）、图床搭建等实用教程，也记录软著申请、饮酒计算器等生活点滴，干货与日常兼具。',
			},
			{
				author: 'snows_l',
				sitenick: '',
				title: 'snows_l',
				desc: '小得盈满！',
				link: 'http://snows-l.site/',
				feed: '',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=37523953&s=640',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=37523953&s=640',
				archs: ['PHP', '服务器'],
				date: '2024-12-09',
				comment: '目前公开信息有限，暂未披露站长近期动态及具体文章内容、领域方向，仅能确认博客名称及访问域名，后续可关注其更新以了解更多详情。',
			},
			{
				author: '梨尽兴',
				sitenick: '',
				title: '梨尽兴',
				desc: 'A place for peace',
				link: 'https://blog.ljx.icu/',
				feed: 'https://blog.ljx.icu/rss.xml',
				icon: 'https://image.lolimi.cn/2026/02/08/6987f1a84ed12.webp',
				avatar: 'https://image.lolimi.cn/2026/02/08/6987f1a84ed12.webp',
				archs: ['Astro', '国内 CDN'],
				date: '2024-12-09',
				comment: '由学生Ljx运营，2025年持续更新至12月。聚焦技术实操，分享Astro AI摘要、博客部署、API使用等干货，也推荐GitHub有趣项目，兼顾全网热榜聚合与生活吐槽，内容实用且多元。',
			},
			{
				author: 'JustPureH20',
				sitenick: '',
				title: 'JustPureH2O',
				desc: '穷方圆平直之情，尽规矩准绳之用',
				link: 'https://justpureh2o.cn/',
				feed: '',
				icon: 'https://pic.wudu.ltd/pic/2025/12/12/693bfade6a038.jpg',
				avatar: 'https://pic.wudu.ltd/pic/2025/12/12/693bfade6a038.jpg',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '由高三学子运营，2024-2025 年持续更新。聚焦高中备考与学习干货，涵盖数物化生语文核心知识点、解题策略，也有编程题解、网图溯源等内容，还记录博客新功能构想，实用且贴合学生需求。',
			},
			{
				author: '酥米的小站',
				sitenick: '',
				title: '酥米的小站',
				desc: '终有一日，寻梦中人',
				link: 'https://www.sumi233.top/',
				feed: 'https://www.sumi233.top/atom.xml',
				icon: 'https://image.lolimi.cn/2026/02/10/698b1884e6695.webp',
				avatar: 'https://image.lolimi.cn/2026/02/10/698b1884e6695.webp',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '2025 年末持续更新，站长刚成年、备战高职考。内容以生活碎碎念为主，记录旅游、打工、游戏日常，也分享 Windows 更新日志、星露谷无显卡服务器搭建等实用教程，温馨又有干货。',
			},
			{
				author: 'Tavre',
				sitenick: '',
				title: 'Tavre',
				desc: '茫茫大海 我与你相遇',
				link: 'https://blog.tavr.top/',
				feed: 'https://blog.tavr.top/rss.xml',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=2987304764&s=640',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=2987304764&s=640',
				archs: ['Astro', 'Vercel'],
				date: '2024-12-09',
				comment: '2025 年持续更新，站长为高中生。内容涵盖实用技术教程（宝塔专业版申请、免费图床搭建、AI 绘画、刷课脚本），也分享澎湃 OS 使用体验、CSGO 游戏日常，干货与生活记录兼具，性价比高。',
			},
			{
				author: '拥抱日出的小屋',
				sitenick: '',
				title: '拥抱日出的小屋',
				desc: '拥抱日出，也拥抱生活',
				link: 'https://ybrc.byside.top/',
				feed: 'https://ybrc.byside.top/rss.xml',
				icon: 'https://ybrc.byside.top/upload/logo.jpg',
				avatar: 'https://ybrc.byside.top/upload/logo.jpg',
				archs: ['Halo', '服务器'],
				date: '2025-12-09',
				comment: '拥抱日出的小屋2025年记录站长学业转折与高中适应，年末作年度总结、期许2026。内容多元，含Nezha监控、宝塔主题更换等技术教程，服务器状态展示，还有随笔、小说创作，兼具实用干货与生活感悟。',
			},
			{
				author: 'THW',
				sitenick: '',
				title: 'THW’s Blog',
				desc: '前途似海，来日方长',
				link: 'https://blog.tianhw.top/',
				feed: 'https://blog.tianhw.top/rss.xml',
				icon: 'https://image.tianhw.top/avatar.webp',
				avatar: 'https://image.tianhw.top/avatar.webp',
				archs: ['Astro', 'EdgeOne'],
				date: '2026-01-18',
				comment: '聚焦Web开发与云原生领域，近期围绕EdgeOne Pages、Astro静态生成等工具展开深度实践，分享自动化图床构建、一键部署方案、纯前端IP获取等硬核教程。',
			},
			{
				author: 'Elykia',
				sitenick: '',
				title: 'Elykia',
				desc: '致以无瑕之人',
				link: 'https://blog.elykia.cn/',
				feed: 'https://blog.elykia.cn/atom.xml',
				icon: 'https://bu.dusays.com/2024/10/25/671b2438203a6.gif',
				avatar: 'https://bu.dusays.com/2024/10/25/671b2438203a6.gif',
				archs: ['Golang', 'EdgeOne'],
				date: '2026-01-23',
				comment: '个人文艺哲思博客，站长近期沉浸于诗意表达与生命哲思创作，文章多探讨存在意义、人性本质与艺术疗愈，领域横跨文学、心理学与存在主义哲学，文风空灵隽永，以隐喻与诗性语言构建精神栖居地，在数字时代守护思想纯净性。',
			},
			{
				author: 'Revelation',
				sitenick: '',
				title: 'Revelation',
				desc: '我在等待，等你回来',
				link: 'https://www.040426.xyz/',
				feed: 'https://www.040426.xyz/atom.xml',
				icon: 'https://image.lolimi.cn/2026/02/08/6987f0ca84a1d.webp',
				avatar: 'https://image.lolimi.cn/2026/02/08/6987f0ca84a1d.webp',
				archs: ['Golang', '服务器'],
				date: '2026-01-25',
				comment: '聚焦于个体在虚妄与真实间的挣扎，通过《若为假希望宁无希望》等文探讨现代人精神困境。内容涵盖存在主义反思、自我解构与重建，领域涉及哲学思辨、心灵成长与文学性社会观察，文风冷峻犀利直指当代生存悖论。',
			},
			{
				author: 'LanM',
				sitenick: '',
				title: 'LanM',
				desc: '蓝莓',
				link: 'https://bluelanm.github.io/my-website/',
				feed: 'https://bluelanm.github.io/my-website/rss.xml',
				icon: 'https://image.lolimi.cn/2026/02/05/6984abce1bbaa.webp',
				avatar: 'https://image.lolimi.cn/2026/02/05/6984abce1bbaa.webp',
				archs: ['GitHub Pages', 'HTML'],
				date: '2026-02-05',
				comment: '蓝莓のBlog近期调Docusaurus配置解加载问题，记建站实践，涉技术建站、个人实践，文风务实。',
			},
			{
				author: 'Karina',
				sitenick: '小窝',
				title: '琳琳的小窝',
				desc: '琳琳的小窝',
				link: 'https://karina.xin/',
				feed: 'https://blog.karina.xin/rss.xml',
				icon: 'https://image.lolimi.cn/2026/02/08/6987ef9f14f0a.webp',
				avatar: 'https://image.lolimi.cn/2026/02/08/6987ef9f14f0a.webp',
				archs: ['GitHub Pages', 'HTML'],
				date: '2026-02-08',
				comment: '近况含Github项目、QQ群。内容有日记、思考、科技数码札、杂谈，涉哲学玄学、记梦绘画，文风带喵系可爱。',
			},
			{
				author: '树萌',
				sitenick: '技术与生活的随笔日记',
				title: '树萌',
				desc: '个人小站，兴趣使然。',
				link: 'https://www.treemoe.cn/',
				feed: 'https://www.treemoe.cn/feed/',
				icon: 'https://oss.treemoe.cn/icon/yui.webp',
				avatar: 'https://oss.treemoe.cn/icon/yui.webp',
				archs: ['Typecho', 'EdgeOne'],
				date: '2026-02-23',
				comment: '树萌的技术博客聚焦Cloudflare创新应用（如R2存储/网络监控）、汉化全流程解析、Typecho/PyCharm深度配置等硬核干货，持续输出开发者实用攻略，兼顾生活杂谈与二次元文化，展现极客浪漫。',
			},
			{
				author: '材料与逻辑萌',
				sitenick: '',
				title: '材料与逻辑',
				desc: '从原子到结构，从数据到洞察。',
				link: 'https://zhyong.site/',
				feed: 'https://zhyong.site/atom.xml',
				icon: 'https://image.lolimi.cn/2026/02/23/699c447427d7d.png',
				avatar: 'https://image.lolimi.cn/2026/02/23/699c447427d7d.png',
				archs: ['HTML', 'EdgeOne'],
				date: '2026-02-23',
				comment: '近期高频更新技术干货，涵盖高分子材料研发、Python/AI自动化、铝合金表面处理等技术，延伸至逻辑思维解析。覆盖材料科学、金属工程等领域，文风硬核技术流，注重实践与理论结合。',
			},
			{
				author: 'Wcowin',
				sitenick: 'web',
				title: 'Wcowin’s Web',
				desc: '循此苦旅，以达星辰',
				link: 'https://wcowin.work/',
				feed: '',
				icon: 'https://image.lolimi.cn/2026/03/02/69a5454d54f05.webp',
				avatar: 'https://image.lolimi.cn/2026/03/02/69a5454d54f05.webp',
				archs: ['Python', 'GitHub Pages'],
				date: '2026-03-02',
				comment: '近期更新MkDocs/Zenical技术文档教程，延伸AI工具评测与极简生产力实践，文风简洁务实，提供可复用的技术方案。',
			},
			{
				author: 'EXYONE',
				sitenick: '自习室',
				title: 'EXYONE',
				desc: '不会前端的.NET程序员不是好程序员',
				link: 'https://www.exyone.me/',
				feed: 'https://www.exyone.me/rss.xml',
				icon: 'https://image.lolimi.cn/2026/03/22/69bf481d86639.png',
				avatar: 'https://image.lolimi.cn/2026/03/22/69bf481d86639.png',
				archs: ['Halo', 'Cloudflare'],
				date: '2026-03-22',
				comment: '',
			},
		],
	},
	{
		name: '『网络组织』',
		desc: '一个人的寂寞，一群人的狂欢',
		entries: [
			{
				author: '开往',
				sitenick: '友链接力!',
				title: '开往',
				desc: '让传统友链“活跃”，让网页相互接力，让流量相互流动，让网络开放起来',
				link: 'https://www.travellings.cn/',
				feed: '',
				icon: 'https://image.lolimi.cn/2026/02/23/699c42f627c85.png',
				avatar: 'https://image.lolimi.cn/2026/02/23/699c42f627c85.png',
				archs: ['VitePress', 'Cloudflare'],
				date: '2025-07-27',
			},
			{
				author: '揪蝉',
				sitenick: '',
				title: '揪蝉',
				desc: '每一次点击都是一次穿越发现',
				link: 'https://hi.jiuchan.org/',
				feed: '',
				icon: 'https://hi.jiuchan.org/logo.svg',
				avatar: 'https://hi.jiuchan.org/logo.svg',
				archs: ['Next.js', 'Cloudflare'],
				date: '2025-06-22',
			},
			{
				author: 'BlogsClub',
				sitenick: '',
				title: 'BlogsClub',
				desc: '个人博客俱乐部',
				link: 'https://www.blogsclub.org/',
				feed: 'https://www.blogsclub.org/feed.xml?sort=time',
				icon: 'https://image.lolimi.cn/2026/02/08/698822ef5e948.webp',
				avatar: 'https://image.lolimi.cn/2026/02/08/698822ef5e948.webp',
				archs: ['Golang', '服务器'],
				date: '2025-06-22',
			},
			{
				author: '笔墨迹',
				sitenick: 'Blogs·CN',
				title: '笔墨迹',
				desc: '致敬还在写博客的我们',
				link: 'https://blogscn.fun/',
				feed: '',
				icon: 'https://photo.xiangming.site/img/blogscn_icon.png',
				avatar: 'https://photo.xiangming.site/img/blogscn_icon.png',
				archs: ['服务器', '国内 CDN'],
				date: '2025-06-22',
			},
		],
	},
	{
		name: '『失联友友』',
		desc: '离别是为了更好的重逢',
		entries: [
			{
				author: '秘柯絮语',
				sitenick: '',
				title: '秘柯絮语',
				desc: 'My Inner Opinion Collection',
				link: 'https://www.mioc.cn/',
				feed: '',
				icon: '',
				avatar: '',
				archs: ['Halo', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'Mioc的博客（2025年更新），站长备考专业考试、即将开启一年船上实习，计划不定期更新。内容涵盖EasyTier异地组网搭建等技术教程，李煜、晏几道诗词赏析，还有航模、视频壁纸分享，兼具技术实践与文学随笔，风格多元。',
			},
		],
	},
	// #endregion
] satisfies FeedGroup[]
