// 鍙嬮摼妫€娴?CLI 闇€瑕佷娇鐢ㄦ樉寮忓鍏ュ拰鐩稿璺緞
import type { FeedGroup } from '../app/types/feed'

export default [
	// #region Clarity
	{
		name: '銆庢竻鏅颁綋楠屻€?,
		desc: '浣跨敤 Clarity 鍗氬涓婚鏋勫缓鐨勭綉绔欍€?,
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: '绾搁箍',
				sitenick: '鎽搁奔澶?,
				title: '绾搁箍鎽搁奔澶?,
				desc: '绾搁箍鑷抽簱涓嶇煡璺紝鏀倝鍒堕湶涓嶆婕?,
				link: 'https://blog.zhilu.site/',
				feed: 'https://blog.zhilu.site/atom.xml',
				icon: 'https://weavatar.com/avatar/47c0f2e82b76d9b10eb3023df9e02e4e3fdbeaf5b74b842063f207971e7fbe7b?s=160',
				avatar: 'https://weavatar.com/avatar/47c0f2e82b76d9b10eb3023df9e02e4e3fdbeaf5b74b842063f207971e7fbe7b?s=160',
				archs: ['Nuxt', 'Vercel'],
				date: '2024-12-09',
				comment: '绾搁箍鎽搁奔澶勫崥瀹紝鑱氱劍鍓嶇寮€鍙戙€佺郴缁熼厤缃笌鏁扮爜浣撻獙锛屽垎浜玍itePress浼樺寲銆佹繁娴呰壊妯″紡绛夋妧鏈寚鍗楋紝鍙夾rchLinux瀹夎銆佹暟鐮佲€滄崱鍨冨溇鈥濆績寰楋紝涔熸湁鐢熸椿鏉傝皥涓庨伩鍧戠粡楠岋紝瀹炵敤鍙堟湁娓╁害銆?,
			},
			{
				author: '姊︾埍鍚冮奔',
				sitenick: '',
				title: '姊︾埍鍚冮奔',
				desc: '浣嗘効鏃ュ瓙娓呴潤鎶ご閬囪鐨勬弧鏄煍鎯?,
				link: 'https://blog.bsgun.cn/',
				feed: 'https://blog.bsgun.cn/atom.xml',
				icon: 'https://lib.bsgun.cn/Hexo-static/img/favicon.ico',
				avatar: 'https://image.lolimi.cn/2026/02/08/6987f2f6639f3.webp',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2024-12-09',
				comment: '姊︾埍鍚冮奔鐨勫崥瀹紙2025骞翠粛鏈夋洿鏂帮級锛岃仛鐒exo鍗氬涓婚榄旀敼锛屽垎浜椤垫牱寮忎紭鍖栥€佷晶杈规爮缁勪欢娣诲姞锛堣瘎璁恒€佸€掕鏃剁瓑锛夈€佸疇鐗╂寕浠剁瓑鏁欑▼锛屼篃鍚紑婧愰」鐩洏鐐逛笌宸ュ叿閮ㄧ讲鏂规锛屼笓娉ㄥ崥瀹㈢編鍖栦笌鍔熻兘鎷撳睍銆?,
			},
			{
				author: '饾櫅饾櫈饾櫒饾櫇饾櫂饾櫏饾櫘',
				sitenick: '',
				title: '饾櫅饾櫈饾櫒饾櫇饾櫂饾櫏饾櫘',
				desc: '浜虹敓婕暱锛屼笉濡ㄥ瑙ｉ攣浜涢矞娲讳綋楠?,
				link: 'https://blog.fis.ink/',
				feed: 'https://blog.fis.ink/atom.xml',
				icon: 'https://file.fis.ink/img/fishcpy/logo.png',
				avatar: 'https://file.fis.ink/img/fishcpy/logo.png',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'fishcpy鐨勫皬鐮寸珯锛?025骞?鏈堟浘閬亣鏈嶅姟鍣ㄦ敾鍑诲苟澶勭悊CDN鐩稿叧闂銆傚唴瀹规兜鐩栬繍缁撮儴缃诧紙1panel鎼缓澶囨绯荤粺銆佸摢鍚掔洃鎺х編鍖栵級銆佽澶囦綋楠屻€侀棶棰樻帓鏌ワ紝涔熸湁闊充箰鎾斁鍣ㄥ垎浜€佺埍鍥藉浘鐗囧悎闆嗙瓑锛屽疄鐢ㄤ笌鎯呮€€鍏煎叿銆?,
			},
			{
				author: '缂樹箣澧?,
				sitenick: '婧愬褰?,
				title: '婧愬褰?,
				desc: '鍑″皹淇鎮熼亾锛屽彥闂粰缂樹箣澧?,
				link: 'https://www.myxz.top/',
				feed: 'https://www.myxz.top/atom.xml',
				icon: 'https://www.myxz.top/avatar.avif',
				avatar: 'https://www.myxz.top/avatar.avif',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2024-12-09',
				comment: '姝嗛涪闃侊紙2025骞村簳鏇存柊锛夛紝绔欓暱灏嗗崥瀹㈣縼绉昏嚦Nuxt妗嗘灦锛岃鍒掓帹杩涙湇鍔¤縼绉讳笌澶氭湇鍔″櫒閮ㄧ讲銆傚唴瀹硅仛鐒uxt鍗氬榄旀敼锛屽惈椤甸潰娣诲姞銆佺粍浠剁編鍖栥€佽瘎璁轰紭鍖栫瓑鏁欑▼锛屼篃璁板綍鍗氬骞冲彴鍙樿縼锛屼笓娉ㄥ墠绔紑鍙戜笌涓€у寲瀹氬埗銆?,
			},
		],
	},
	// #endregion
	// #region 缃戜笂閭诲眳
	{
		name: '銆庣綉涓婇偦灞呫€?,
		desc: '鍝斺€斺€斿暤鈥斺€旂數娉㈤€氳涓紝娆㈣繋甯告潵涓查棬銆?,
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: 'klcdm',
				sitenick: '鏈戒笜绉嬮洦',
				title: '鏈戒笜绉嬮洦',
				desc: '涓€瀹氫細鍜屽枩娆㈢殑浜哄湪澶忔棩澶滄櫄鐗垫墜鎱㈡',
				link: 'https://koxiuqiu.cn/',
				feed: 'https://koxiuqiu.cn/atom.xml',
				icon: 'https://koxiuqiu.cn/img/avatar/avatar.png',
				avatar: 'https://koxiuqiu.cn/img/avatar/xiaokeb.png',
				archs: ['Hexo', '鏈嶅姟鍣?],
				date: '2024-12-09',
				comment: '灏忔煰鐨勬溄涓樼闆紙2025骞村簳淇暣鏂颁富棰橈級锛岃繎鏈熻皟鏁翠釜浜虹姸鎬佸悗灏嗘仮澶嶅鏇淬€傚唴瀹逛互鐢熸椿鏃ュ織銆佹湀搴?骞村害鎬荤粨涓轰富锛岃皥鍙婁翰鎯呫€佷唬闄呰蹇电瓑鎰熸偀锛屼篃鏈夋儏鎰熸潅璇笌鏆傚埆绲锛屾弧鍚釜浜虹湡瀹炴€濈华涓庣敓娲荤儫鐏皵銆?,
			},
			{
				author: '瀹夌煡楸?,
				sitenick: '',
				title: '瀹夌煡楸?,
				desc: '鐢熸椿鏄庢湕锛屼竾鐗╁彲鐖?,
				link: 'https://blog.anheyu.com/',
				feed: 'https://blog.anheyu.com/atom.xml',
				icon: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				avatar: 'https://npm.elemecdn.com/anzhiyu-blog-static@1.0.4/img/avatar.jpg',
				archs: ['Golang', 'EdgeOne'],
				date: '2024-12-09',
				comment: '瀹夊拰楸肩殑鍗氬锛?025骞村簳鎸佺画鏇存柊锛夛紝鑱氱劍鍓嶇鎶€鏈笌Anheyu-App鐩稿叧锛屽垎浜獵SS鏂版柟妗堛€丷eact婕忔礊銆丆SRF鏀诲嚮绛夋妧鏈В鏋愶紝鍙婂簲鐢ㄥ畨瑁呰縼绉绘暀绋嬶紝涔熷惈Mac浣跨敤浣撻獙銆佹姹夋梾娓告棩蹇椾笌骞村害鎬荤粨锛屾妧鏈疄鐢ㄤ笖鍏奸【鐢熸椿姘旀伅銆?,
			},
			{
				author: 'FrWalker',
				sitenick: '',
				title: 'FrWalker',
				desc: '鍚闆紝闂槦杈帮紝闅忓績褰掆湪',
				link: 'https://blog.frwalker.top/',
				feed: 'https://blog.frwalker.top/atom.xml',
				icon: 'https://image.lolimi.cn/2025/07/22/687f0ffd971b9.ico',
				avatar: 'https://image.lolimi.cn/2025/07/22/687f0ffd971b9.ico',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '绔欓暱杩戞湡涓撴敞鍒涗綔锛屽崥瀹互Linux鎶€鏈笌寮€婧愰」鐩负鏍稿績銆傛湁Linux绯荤粺瀹夎銆侀厤缃暀绋嬶紝涔熷垎浜紑婧愰」鐩疄璺电粡楠屻€傝嚧鍔涗簬涓篖inux鐖卞ソ鑰呬笌寮€鍙戣€呮彁渚涗笓涓氱煡璇嗭紝鍔╁姏鍦ㄥ紑婧愪笘鐣屾帰绱㈠墠琛屻€?',
			},
			{
				author: '闄嗗皬鍚疜airo',
				sitenick: '',
				title: '闄嗗皬鍚疜airo',
				desc: '寰€鑰呬笉璋忥紝鏉ヨ€呭彲杩?,
				link: 'https://blog.zonox.top/',
				feed: 'https://blog.zonox.top/feed/',
				icon: 'https://bu.dusays.com/2025/03/14/67d3fbedaa1c6.webp',
				avatar: 'https://bu.dusays.com/2025/03/14/67d3fbedaa1c6.webp',
				archs: ['Typecho', 'Cloudflare'],
				date: '2024-12-09',
				comment: '绔欓暱杩戞湡鍒涗綔鐑儏楂樻定銆傚崥瀹㈡枃绔犻泦涓簬鍔ㄦ极璧勮銆佹父鎴忔潅璋堛€傚垎浜柊鐣姩鎬併€佺粡鍏稿姩婕В璇伙紝涔熸湁娓告垙鐜╂硶鎶€宸с€佽涓氱儹鐐硅璁恒€傛墡鏍笰CG棰嗗煙锛屼负鐖卞ソ鑰呮惌寤轰氦娴佸垎浜殑浼樿川骞冲彴銆?',
			},
			{
				author: '钁辫嫇sama',
				sitenick: '钁辫嫇灏忕瓚',
				title: '钁辫嫇灏忕瓚',
				desc: '椋庡甫鏉ヤ簡鏁呬簨鐨勭瀛愶紝鏃堕棿浣垮叾鍙戣娊銆?,
				link: 'https://blog.ciraos.top/',
				feed: 'https://blog.ciraos.top/atom.xml',
				icon: 'https://i.p-i.vip/135/20260102-6957b41708b60.png',
				avatar: 'https://i.p-i.vip/135/20260102-6957b41708b60.png',
				archs: ['Hexo', '鍥藉唴 CDN'],
				date: '2024-12-09',
				comment: '璇ュ崥瀹㈢珯闀垮綋涓嬩笓娉ㄥ垱浣滐紝鏂囩珷澶氫负杞欢璧勬簮鍒嗕韩鍙婁娇鐢ㄦ暀绋嬶紝鍍忓悇绫诲疄鐢ㄥ伐鍏枫€佸姙鍏蒋浠剁瓑銆備篃娑电洊鐢佃剳绯荤粺浼樺寲鎶€宸э紝鑱氱劍鏁扮爜杞欢棰嗗煙锛屼负鐢ㄦ埛鎻愪緵渚挎嵎楂樻晥鐨勪娇鐢ㄦ寚鍗椾笌璧勬簮銆?',
			},
			{
				author: 'Imz',
				sitenick: '',
				title: 'Imz',
				desc: '浠版湜鏄熺┖锛岃剼韪忓疄鍦般€?,
				link: 'https://blog.imz.me/',
				feed: '',
				icon: 'https://pic.wudu.ltd/pic/2025/10/04/68e12d685b3a5.webp',
				avatar: 'https://pic.wudu.ltd/pic/2025/10/04/68e12d685b3a5.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: 'imz鐨勫皬绔欙紙2025骞?0鏈堟洿鏂版爣璇級锛岃仛鐒﹀鎶€鏈鍩燂紝鍒嗕韩Chrome澶氬紑銆佽棰戜笅杞界瓑杞欢浣跨敤鏁欑▼锛屽強Alist-Helper闂瑙ｅ喅銆丠exo鎻掍欢閰嶇疆绛夊唴瀹癸紝娑夊強JS銆丏ocker銆乂ue绛夋妧鏈紝鍏煎叿瀹炵敤鎶€宸т笌鎶€鏈疄璺点€?,
			},
			{
				author: '鍞愬織杩?,
				sitenick: '',
				title: '鍞愬織杩?,
				desc: '绔嬪織鎴愪负涓€鍚嶆灦鏋勫笀',
				link: 'https://fe32.top/',
				feed: 'https://fe32.top/atom.xml',
				icon: 'https://bu.dusays.com/2022/05/02/626f92e193879.jpg',
				avatar: 'https://bu.dusays.com/2022/05/02/626f92e193879.jpg',
				archs: ['Hexo', '鏈嶅姟鍣?],
				date: '2024-12-09',
				comment: '鍞愬織杩滅殑鍗氬锛坒e32.top锛夛紝鑱氱劍鍓嶇鎶€鏈笌鏈嶅姟鍣ㄦ惌寤恒€傚唴瀹规兜鐩朒exo+Butterfly鍗氬鎼缓銆丠TTP鍗忚銆丆SS瑙勮寖涓庡姩鐢诲簱鎺ㄨ崘銆乂ue3闂瑙ｅ喅绛夊墠绔共璐э紝涔熸湁CentOS瀹夎銆乂Mware閰嶇疆绛夋湇鍔″櫒鏁欑▼锛屽疄鐢ㄦ妧宸т赴瀵岋紝鎶€鏈鍚戞槑纭€?,
			},
			{
				author: 'Mo鐨勮浜嬬翱',
				sitenick: '',
				title: 'Mo鐨勮浜嬬翱',
				desc: '涓囧勾楦界帇锛屽搱鍝圤vO',
				link: 'https://blog.xiowo.net/',
				feed: 'https://blog.xiowo.net/atom.xml',
				icon: 'https://image.lolimi.cn/2025/07/22/687f0bd346429.png',
				avatar: 'https://image.lolimi.cn/2025/07/22/687f0bd346429.png',
				archs: ['Hexo', 'Netlify'],
				date: '2024-12-09',
				comment: 'MortalCat鐨勫崥瀹紙2025骞存寔缁洿鏂帮級锛岃仛鐒exo鍗氬鎼缓涓庣編鍖栵紝鍒嗕韩瀹夌煡楸间富棰橀厤缃€乀wikoo璇勮浼樺寲绛夋暀绋嬶紝涔熸兜鐩朎mby浠ｇ悊銆丄ndroid缃戠粶淇銆丟itHub鍔犻€熺瓑宸ュ叿浣跨敤鎶€宸э紝鍏煎叿鎶€鏈瑪璁颁笌瀹炵敤鎸囧崡锛屽共璐ф弧婊°€?,
			},
			{
				author: '澹逛汉灏忕珯',
				sitenick: '',
				title: '澹逛汉灏忕珯',
				desc: 'Trust the process.',
				link: 'https://www.xscnet.cn/',
				feed: 'https://www.xscnet.cn/atom.xml',
				icon: 'https://www.xscnet.cn/avatar1.jpg',
				avatar: 'https://www.xscnet.cn/avatar1.jpg',
				archs: ['Vue', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'Mete0r鐨勫９浜哄皬绔欙紙2025骞?0鏈堣嚧姝夋殏鏇达級锛岀珯闀夸负楂樹笁瀛︾敓锛屽皢鍦?026骞?鏈堥珮鑰冨悗鍥炲綊銆傚唴瀹瑰惈绔欑偣CDN浼樺寲銆佹暟鐮佹帹鑽愩€侀煶涔愬垎浜€佹棩甯稿皬缁擄紝杩樺紑鍙戣繃娓告垙瀛樻。鍚屾宸ュ叿锛屽吋鍏峰缓绔欐妧鏈€佺敓娲荤偣婊翠笌鍏磋叮鍒嗕韩銆?,
			},
			{
				author: 'AcoFork',
				sitenick: '',
				title: 'AcoFork',
				desc: 'Protect What You Love!',
				link: 'https://blog.acofork.com/',
				feed: 'https://blog.acofork.com/rss.xml',
				icon: 'https://q2.qlogo.cn/headimg_dl?dst_uin=2726730791&spec=5',
				avatar: 'https://q2.qlogo.cn/headimg_dl?dst_uin=2726730791&spec=5',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-12-09',
				comment: '浜屽弶鏍戞爲鐨勫崥瀹紙2025骞村簳鏇存柊锛夛紝杩戞湡绔欑偣閬ぇ瑙勬āDDoS鏀诲嚮銆傚唴瀹硅仛鐒erverless銆佷簯鍑芥暟绛夋妧鏈紝鍒嗕韩Umami閮ㄧ讲銆佸尶鍚嶆枃浠朵笂杞藉櫒鎼缓銆佽繙绋嬫帶鏈虹瓑鏁欑▼锛屼篃娑夊強绫冲搱娓窤I閫嗘敼涓嶲QBot寮€鍙戯紝鎶€鏈疄鐢ㄤ笖鑱氱劍楂樻晥閮ㄧ讲銆?,
			},
			{
				author: '寮犳椽Heo',
				sitenick: '',
				title: '寮犳椽Heo',
				desc: '鍒嗕韩璁捐涓庣鎶€鐢熸椿',
				link: 'https://blog.zhheo.com/',
				feed: 'https://blog.zhheo.com/atom.xml',
				icon: 'https://image.lolimi.cn/2025/07/22/687f0d0ee6fd3.png',
				avatar: 'https://image.lolimi.cn/2025/07/22/687f0d0ee6fd3.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '寮犳椽Heo鐨勫崥瀹紙2026骞存洿鏂帮級锛岃仛鐒﹁璁′笌绉戞妧鐢熸椿銆傚唴瀹瑰惈Mac/iOS杞欢鎺ㄨ崘銆乮Phone17涓婃墜浣撻獙銆丗inal Cut Pro鍓緫鎶€宸с€佹櫤鑳藉灞呮帴鍏ョ瓑瀹炵敤缁忛獙锛屼篃鏈夐棽鑱婃潅璋堜笌骞村害鍗氫富鎺ㄨ崘锛屽吋鍏锋暟鐮佸共璐т笌鐢熸椿姘旀伅銆?,
			},
			{
				author: '澶滆交Blog',
				sitenick: '',
				title: '澶滆交Blog',
				desc: '涓€涓汉',
				link: 'https://blog.yeqing.net/',
				feed: 'https://blog.yeqing.net/atom.xml',
				icon: 'https://list.yeqing.net/d/oss/image/i/2025/05/15/62868e67dff91285992985db0cce57d5.webp',
				avatar: 'https://list.yeqing.net/d/oss/image/i/2025/05/15/62868e67dff91285992985db0cce57d5.webp',
				archs: ['Hexo', '鍥藉唴 CDN'],
				date: '2024-12-09',
				comment: '澶滆交Blog锛?025骞存洿鏂帮級锛岀珯闀挎彁鍙婄柌鎯兂鍋滀笅锛屽惎鐢ㄦ柊鍩熷悕qzq.im銆傚唴瀹硅仛鐒﹀厤璐逛簰鑱旂綉鏈嶅姟銆乂PS涓嶤DN锛堥浂涔濄€佹鍠典簯绛夛級浣跨敤浣撻獙锛屼篃鍚殢鏈哄浘鐗嘇PI鏂囨。鍒朵綔锛屼富鎵撶綉缁滄湇鍔℃祴璇勪笌瀹炵敤璧勬簮鍒嗕韩銆?,
			},
			{
				author: '鉂栨槦娓棊Star鈽?,
				sitenick: '',
				title: '鉂栨槦娓棊Star鈽?,
				desc: '浠ュ崥瀹㈣褰曠敓娲讳笌鐑埍锛?,
				link: 'https://blog.starsharbor.com/',
				feed: 'https://blog.starsharbor.com/atom.xml',
				icon: 'https://q.qlogo.cn/g?b=qq&nk=288313&s=640',
				avatar: 'https://q.qlogo.cn/g?b=qq&nk=288313&s=640',
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-12-09',
				comment: '璁板綍寤虹珯澶氬懆骞村巻绋嬩笌涓婃捣鏃呰绾康銆傚唴瀹规兜鐩朒armonyOS NEXT绯荤粺浣撻獙銆乻olitude涓婚閰嶇疆锛堝瓧浣?鍙嬮摼/鏁版嵁缁熻锛夌瓑鎶€鏈垎浜紝涔熸湁鍘熺鐗堟湰姊崇悊銆侀ギ鍝佹祴璇勩€佸崕涓烘墜琛ㄤ娇鐢ㄨ褰曪紝鍏煎叿鎶€鏈疄璺典笌鐢熸椿闅忕瑪锛岄鏍煎鍏冦€?,
			},
			{
				author: 'Xuan\'s blog',
				sitenick: '',
				title: 'Xuan\'s blog',
				desc: '鍒嗕韩鎶€鏈暀绋嬪拰瀛︿範绗旇',
				link: 'https://blog.ybyq.wang/',
				feed: 'https://blog.ybyq.wang/feed/',
				icon: 'https://blog.ybyq.wang/usr/themes/handsome/assets/img/avatar.png',
				avatar: 'https://blog.ybyq.wang/usr/themes/handsome/assets/img/avatar.png',
				archs: ['Typecho', '鍥藉唴 CDN'],
				date: '2024-12-09',
				comment: 'Xuan\'s blog锛?025骞?1鏈堟洿鏂帮級锛岀珯闀胯幏椤圭洰鍔冲姟璐癸紝璁板綍鏅氶湠銆佷腑绉嬫父璁扮瓑鐢熸椿鐐规淮銆傚唴瀹规兜鐩朥mami鍗囩骇銆乀ypecho鍗氬杩愮淮锛堜富棰樼編鍖栥€佹彃浠剁洃鎺х瓑锛夋暀绋嬶紝鍙奊PT鑱婂ぉ搴旂敤銆佸仴韬埧绠＄悊绯荤粺寮€鍙戝疄璺碉紝鍏煎叿鎶€鏈共璐т笌鐢熸椿闅忕瑪銆?,
			},
			/* {
				author: '绉樻煰绲',
				sitenick: '',
				title: '绉樻煰绲',
				desc: 'My Inner Opinion Collection',
				link: 'https://www.mioc.cn/',
				feed: 'https://www.mioc.cn/rss.xml',
				icon: 'https://www.mioc.cn/upload/LOGO.svg',
				avatar: 'https://www.mioc.cn/upload/LOGO.svg',
				archs: ['Halo', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'Mioc鐨勫崥瀹紙2025骞存洿鏂帮級锛岀珯闀垮鑰冧笓涓氳€冭瘯銆佸嵆灏嗗紑鍚竴骞磋埞涓婂疄涔狅紝璁″垝涓嶅畾鏈熸洿鏂般€傚唴瀹规兜鐩朎asyTier寮傚湴缁勭綉鎼缓绛夋妧鏈暀绋嬶紝鏉庣厹銆佹檹鍑犻亾璇楄瘝璧忔瀽锛岃繕鏈夎埅妯°€佽棰戝绾稿垎浜紝鍏煎叿鎶€鏈疄璺典笌鏂囧闅忕瑪锛岄鏍煎鍏冦€?,
			},
			*/
			{
				author: '鐧鹃噷鍗氬',
				sitenick: '',
				title: '鐧鹃噷鍗氬',
				desc: '涓€涓珮涓敓鐨勫崥瀹?,
				link: 'https://blog.my0811.cn/',
				feed: 'https://blog.my0811.cn/rss.xml',
				icon: 'https://blog.my0811.cn/favicon.ico',
				avatar: 'https://blog.my0811.cn/favicon.ico',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-12-09',
				comment: '鐧鹃噷鍗氬锛?025骞?鏈堟洿鏂帮級锛屼笓娉ㄦ妧鏈疄璺典笌瀹炵敤鏁欑▼銆傚唴瀹规兜鐩朅ndroid閫嗗悜锛堝柕绐濊璐︾牬瑙ｏ級銆丵wen3-Coder澶фā鍨嬪畨瑁呫€丗uwari鍗氬杩界暘鍒楄〃鎺ュ叆锛屽強Python姝ユ暟鑷姩鍖栬剼鏈紑鍙戯紝鑱氱劍閫嗗悜宸ョ▼銆丄I缂栫▼涓庡崥瀹㈠畾鍒讹紝骞茶揣瀹炵敤涓旇惤鍦版€у己銆?,
			},
			{
				author: 'AirTouch',
				sitenick: '',
				title: 'AirTouch',
				desc: '宀╅棿鐞夌拑浜戦棿鏈?,
				link: 'https://xsl.im/',
				feed: 'https://www.xsl.im/atom.xml',
				icon: 'https://www.xsl.im/avatar.webp',
				avatar: 'https://www.xsl.im/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: 'AirTouch鐨勫崥瀹紙2025骞?1鏈堟寔缁洿鏂帮級锛岃繎鏈熸洿鏂癝tellar涓婚銆傚唴瀹硅仛鐒︽妧鏈姌鑵句笌椤圭洰鍒嗕韩锛屽惈Artalk璇勮鍖洪厤缃€丠exo AI鎽樿绛夊崥瀹紭鍖栨暀绋嬶紝Librechat AI閮ㄧ讲銆佷复鏃堕偖绠辨惌寤虹瓑椤圭洰鎺ㄨ崘锛岃繕鏈塚PS娴嬭瘎涓庣郴缁熼棶棰樿В鍐虫柟妗堬紝鎶€鏈疄鐢ㄤ笖瑕嗙洊澶氬厓鍦烘櫙銆?,
			},
			{
				author: '鍙舵朝甯?,
				sitenick: '',
				title: '鍙舵朝甯?,
				desc: '鎰忎箟鏄嚜宸辫祼浜堢殑',
				link: 'https://blog.418121.xyz/',
				feed: 'https://blog.418121.xyz/rss2.xml',
				icon: 'https://blog.418121.xyz/images/avatar.webp',
				avatar: 'https://blog.418121.xyz/images/avatar.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '鍙舵朝甯岀殑鍗氬锛屽唴瀹规兜鐩朣olitude涓婚榄旀敼銆佹棩甯搁殢绗斾笌鎽勫奖浣滃搧锛屼篃鍒嗕韩鈥滃皧閲嶅垎姝р€濃€滅弽鎯滅溂鍓嶁€濈殑浜虹敓鎰熸偀銆傛棤鏄庣‘杩戞湡鐗规畩杩戝喌锛岃仛鐒︿釜浜虹敓娲昏褰曘€佸崥瀹㈡姌鑵句笌褰卞儚琛ㄨ揪锛岄鏍肩粏鑵昏创鍚堢敓娲汇€?,
			},
			{
				author: '灏忎寒鐨勯儴钀介榿',
				sitenick: '',
				title: '灏忎寒鐨勯儴钀介榿',
				desc: '娆叉湜浠ユ彁鍗囩儹蹇憋紝姣呭姏浠ョ（骞抽珮灞?,
				link: 'https://blog.752132.xyz/',
				feed: 'https://blog.752132.xyz/atom.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6e1799c43.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6e1799c43.png',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '灏忎寒鐨勯儴钀介榿锛?025骞?鏈堟洿鏂帮級锛岀珯闀块儴缃蹭簡涓汉涓婚〉銆佸崥瀹㈢瓑澶氫釜瀹炵敤椤圭洰銆傚唴瀹硅仛鐒exo鐩稿叧锛屽惈鍗氬鎼缓銆佷富棰樼編鍖栥€佷晶杈规爮娣诲姞鈥滃巻鍙蹭笂鐨勪粖澶┾€濄€佸浘搴婃惌寤虹瓑鏁欑▼锛屼篃璁板綍缃戠珯宕╂簝鍚庨噸鏋勭粡楠岋紝涓撴敞鍗氬鎶樿吘涓庡疄鐢ㄦ妧鏈垎浜€?,
			},
			{
				author: '闊╁皬闊╁崥瀹?,
				sitenick: '',
				title: '闊╁皬闊╁崥瀹?,
				desc: '杩愭皵鏄鍒掍箣澶栫殑涓滆タ.',
				link: 'https://www.vvhan.com/',
				feed: 'https://www.vvhan.com/rss.xml',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=1655466387&s=640',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=1655466387&s=640',
				archs: ['Astro', 'EdgeOne'],
				date: '2024-12-09',
				comment: '闊╁皬闊╁崥瀹㈢殑涓汉鍗氬銆傜珯闀垮潥鎸佹洿鏂帮紝鍒嗕韩涓汉鎬濊€冧笌鐢熸椿鐐规淮銆傛枃绔犻鏍艰繍姘旀槸璁″垝涔嬪鐨勪笢瑗?銆傝褰曚釜浜烘垚闀垮巻绋嬶紝鍒嗕韩鐢熸椿鎰熸偀涓庣粡楠岋紝娆㈣繋璁块棶浜ゆ祦銆?,
			},
			{
				author: '涓滄柟鏈堝垵',
				sitenick: '',
				title: '涓滄柟鏈堝垵',
				desc: '鍒嗕韩鏈夎叮浣嗗張鏃犺亰鐨勪笢瑗裤€?,
				link: 'https://blog.biuxin.com/',
				feed: 'https://blog.biuxin.com/atom.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6de94d5c3.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6de94d5c3.png',
				archs: ['Golang', '鏈嶅姟鍣?],
				date: '2024-12-09',
				comment: 'Biuxin鐨勫崥瀹紙2025骞存寔缁洿鏂帮級锛岃仛鐒︽妧鏈疄璺典笌鐢熸椿闅忕瑪銆傚唴瀹瑰惈Typecho鍗氬浼樺寲銆佹湇鍔″櫒杩愮淮绛夊疄鐢ㄦ妧宸э紝涔熻褰曟棩甯告劅鎮熶笌鍏磋叮鍒嗕韩锛屽吋鍏疯惤鍦版€ф妧鏈共璐т笌鐪熷疄鐢熸椿鎬濈华锛岄鏍肩畝绾︿笖鍐呭澶氬厓銆?,
			},
			{
				author: '鑳滃ぉ鍗婂瓙',
				sitenick: '',
				title: '鑳滃ぉ鍗婂瓙',
				desc: '浜嬪凡鑷虫锛屽厛鍚冮キ鍚ю煒?,
				link: 'https://blog.291055.xyz/',
				feed: '',
				icon: 'https://i1.wp.com/ruom.wuaze.com/i/2024/11/02/166823.webp',
				avatar: 'https://i1.wp.com/ruom.wuaze.com/i/2024/11/02/166823.webp',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '鑳滃ぉ鍗婂瓙鐨勪釜浜哄崥瀹€傜珯闀垮潥鎸佹洿鏂帮紝鍒嗕韩涓汉鎬濊€冧笌鐢熸椿鐐规淮銆傛枃绔犻鏍间簨宸茶嚦姝わ紝鍏堝悆楗惂馃構銆傝褰曚釜浜烘垚闀垮巻绋嬶紝鍒嗕韩鐢熸椿鎰熸偀涓庣粡楠岋紝娆㈣繋璁块棶浜ゆ祦銆?,
			},
			{
				author: 'Eilo',
				sitenick: '',
				title: 'Eilo',
				desc: '绛夌瓑鎴戣涓€涓?,
				link: 'https://aptu.net/',
				feed: 'https://aptu.net/rss.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6dc76e073.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6dc76e073.png',
				archs: ['HTML', 'Netlify'],
				date: '2024-12-09',
				comment: '鏃犵壒娈婅繎鏈熷彉鍔ㄣ€傚唴瀹硅仛鐒︽妧鏈疄璺典笌鐢熸椿闅忕瑪锛屾兜鐩栨湇鍔″櫒杩愮淮銆佽蒋浠跺疄鐢ㄦ妧宸х瓑骞茶揣锛屼篃璁板綍鏃ュ父鎰熸偀涓庡叴瓒ｇ偣婊达紝鍏煎叿鎶€鏈惤鍦版€т笌鐢熸椿鐪熷疄鎰燂紝椋庢牸绠€娲佷笖鍐呭澶氬厓銆?,
			},
			{
				author: '鏂伴攼鍗氬',
				sitenick: '',
				title: '鏂伴攼鍗氬',
				desc: '璁板綍瀛︿範涓庡垎浜祫婧?,
				link: 'https://www.xrbk.cn/',
				feed: 'https://www.xrbk.cn/atom.xml',
				icon: 'https://www.xrbk.cn/favicon.png',
				avatar: 'https://www.xrbk.cn/favicon.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '鏃犵壒娈婅繎鏈熻繎鍐点€傚唴瀹规兜鐩栨妧鏈疄璺点€佺敓娲婚殢绗斾笌鍏磋叮鍒嗕韩锛屽惈寤虹珯鐩稿叧鎶€宸с€佹棩甯告劅鎮熺瓑锛屽吋鍏峰疄鐢ㄥ共璐т笌鐪熷疄鐢熸椿姘旀伅锛岄鏍肩畝绾﹁川鏈达紝鍐呭澶氬厓璐村悎涓汉琛ㄨ揪銆?,
			},
			{
				author: '鏄熻景銇瑪璁?,
				sitenick: '',
				title: '鏄熻景銇瑪璁?,
				desc: '浠ｇ爜 |鎬濊€?|鍒嗕韩 | 閲嶅',
				link: 'https://blog.strarry.top/',
				feed: '',
				icon: 'https://blog.strarry.top/avatar.jpg',
				avatar: 'https://blog.strarry.top/avatar.jpg',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '鍐呭娑电洊鎶€鏈疄璺点€佺敓娲婚殢绗斾笌鍏磋叮鍒嗕韩锛屽惈寤虹珯鐩稿叧鎶€宸с€佹棩甯告劅鎮熺瓑瀹炵敤骞茶揣涓庝釜浜烘€濈华锛岄鏍兼竻鏂扮畝绾︼紝鍏煎叿鎶€鏈惤鍦版€т笌鐢熸椿姘旀伅锛屽唴瀹瑰鍏冭创鍚堜釜浜鸿〃杈俱€?,
			},
			{
				author: '澶╂捣鍗氬',
				sitenick: '',
				title: '澶╂捣鍗氬',
				desc: '寤虹珯缁忛獙璁板綍锛屽疄鐢ㄥ伐鍏锋帹鑽愶紝鍏嶈垂璧勬簮鍒嗕韩銆?,
				link: 'https://woolyun.com',
				feed: 'https://woolyun.com/feed/',
				icon: 'https://i.p-i.vip/135/20251129-692a6da7aa977.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6da7aa977.png',
				archs: ['Typecho', 'Cloudflare'],
				date: '2024-12-09',
				comment: '澶╂捣鍗氬锛坵oolyun.com锛夌敱澶╂捣鐗ф瓕杩愯惀锛?025骞?1鏈堟寔缁洿鏂般€傚唴瀹规兜鐩栧ソ鐗╁垎浜紙PS2025銆佽繀闆?2绛夛級銆丄I鐩稿叧銆佷簯鏈嶅姟鍣ㄧ煡璇嗐€佹妧鏈疄鎿嶅強缃戠粶瀹夊叏鎶€宸э紝瀹炵敤涓斿鍏冦€?,
			},
			{
				author: 'AYaka',
				sitenick: '',
				title: 'AYaka',
				desc: '淇濇姢浣犳墍鐖憋紒鉂?,
				link: 'https://blog.ayaka0.top/',
				feed: 'https://blog.ayaka0.top/rss.xml',
				icon: 'https://pic.wudu.ltd/pic/2025/08/23/68a92f8655ba4.webp',
				avatar: 'https://pic.wudu.ltd/pic/2025/08/23/68a92f8655ba4.webp',
				archs: ['Astro', 'Cloudflare'],
				date: '2024-12-09',
				comment: 'AYaka Blog锛坆log.ayaka0.top锛夌敱Kamisato Ayaka杩愯惀锛?025骞?鏈堥珮棰戞洿鏂帮紝娆㈣繋浜ゆ崲鍙嬮摼銆傚唴瀹硅仛鐒︽妧鏈鍩燂紝鍚獿inux銆佸墠绔€丳ython銆丟it銆丄stro鍗氬鎼缓绛夊共璐э紝杩樻湁鎺掔増宸ュ叿鏁呴殰淇銆丄I椤圭洰浼樺寲绛夊疄鐢ㄥ垎浜€?,
			},
			{
				author: 'Noah',
				sitenick: '',
				title: 'Noah',
				desc: '鍔姏鍘诲彂鍏夛紝鑰屼笉鏄鐓т寒',
				link: 'https://blog.noah0932.top/',
				feed: 'https://blog.noah0932.top/rss.xml',
				icon: 'https://cdn.tulan.cyou/noah/2025/07/26/b_5255bd8e31082e2a4332c4eb4172686e.jpg',
				avatar: 'https://cdn.tulan.cyou/noah/2025/07/26/b_5255bd8e31082e2a4332c4eb4172686e.jpg',
				archs: ['Hexo', '鍥藉唴 CDN'],
				date: '2024-12-09',
				comment: 'Noah銇瓸log锛坆log.noah0932.top锛夎繎鏈熸椿璺冩洿鏂帮紝鍐呭澶氬厓銆傛兜鐩栨妧鏈共璐э紙Hexo闂瑙ｅ喅銆丆loudFlare閮ㄧ讲绛夛級銆侀偖绠?鏁欒偛閭鐢宠銆丏NS瀵规瘮锛屼篃鏈夋棩甯告劅鎮熴€佹槑淇＄墖娓╂儏娲诲姩锛屽疄鐢ㄤ笌娓╂儏鍏煎叿銆?,
			},
			{
				author: '绛栨煰',
				sitenick: '',
				title: '绛栨煰',
				desc: '鏃剁煫棣栬€岄亹瑙?,
				link: 'https://blog.xomoe.cn/',
				feed: 'https://blog.xomoe.cn/rss.xml',
				icon: 'https://blog.xomoe.cn/_astro/touxiang.DuQ7TJxD_ZbtHS7.webp',
				avatar: 'https://blog.xomoe.cn/_astro/touxiang.DuQ7TJxD_ZbtHS7.webp',
				archs: ['Astro', '鍥藉唴 CDN'],
				date: '2024-12-09',
				comment: '2025骞?-10鏈堟寔缁洿鏂帮紝鑱氱劍闊充箰涓庢妧鏈鍩熴€傛敹褰曞崕璇€佹棩璇€佷簩娆″厓绛夊鍏冩洸椋庢瓕鏇诧紝涔熷垎浜獿inux閰嶇疆銆佸崥瀹富棰樹紭鍖栫瓑鎶€鏈共璐э紝鍐呭涓板瘜涓斿疄鐢ㄣ€?,
			},
			{
				author: '闈掓姘旂悆',
				sitenick: '',
				title: '闈掓姘旂悆',
				desc: '鍒嗕韩缃戠粶瀹夊叏涓庣鎶€鐢熸椿',
				link: 'https://blog.qjqq.cn/',
				feed: 'https://blog.qjqq.cn/atom.xml',
				icon: 'https://q2.qlogo.cn/headimg_dl?dst_uin=1645253&spec=640',
				avatar: 'https://q2.qlogo.cn/headimg_dl?dst_uin=1645253&spec=640',
				archs: ['Hexo', '鍥藉唴 CDN'],
				date: '2024-12-09',
				comment: '闈掓姘旂悆鏄笓娉ㄧ綉缁滃畨鍏ㄤ笌绉戞妧鐢熸椿鐨勪釜浜烘妧鏈崥瀹紝鎸佺画鍒嗕韩瀹炴垬瀵煎悜鐨勫缓绔欐暀绋嬶紙濡係olitude鏃ュ巻绯荤粺銆丠exo鑷姩鍖栭儴缃诧級銆佽交閲忓寲缃戠洏鏂规锛圸File/Docker閮ㄧ讲锛夈€丄PI鎺ュ彛寮€鍙戯紙QQ/寰俊鐢熸€侊級鍙婅繍缁翠紭鍖栫粡楠屻€傚崥涓昏繎鏈熺簿杩涗簬鑷姩鍖朣SL璇佷功鎺ㄩ€併€佽竟缂樿绠楀姞閫燂紙EdgeOne锛夌瓑鎶€鏈帰绱紝椤甸潰椋庢牸绠€绾﹀疄鐢紝鑷村姏浜庨€氳繃浠ｇ爜鐗囨涓庡浘鏂囩粨鍚堥檷浣庢妧鏈惤鍦伴棬妲涳紝鏄紑鍙戣€呬笌鏋佸鎺㈢储浣庢垚鏈В鍐虫柟妗堢殑浼樿川鍙傝€冩簮銆?,
			},
			{
				author: '鍒鎴戠殑闀滃ご鐩?,
				sitenick: '',
				title: '鍒鎴戠殑闀滃ご鐩?,
				desc: 'AI鎮﹀垱路鍒涢€犱笉鍚岋紒',
				link: 'https://blog.bornforthis.cn/',
				feed: 'https://blog.bornforthis.cn/atom.xml',
				icon: 'https://weavatar.com/avatar/d2262986371318821a2cfe4dc37a18bd62af3e7e5d531301c87f6066a483faa0?d=letter&letter=A',
				avatar: 'https://weavatar.com/avatar/d2262986371318821a2cfe4dc37a18bd62af3e7e5d531301c87f6066a483faa0?d=letter&letter=A',
				archs: ['Hexo', '鏈嶅姟鍣?],
				date: '2024-12-09',
				comment: '鍒鎴戠殑闀滃ご鐩栨槸缂栫▼瀵煎笀鎮﹀垱鐨勪釜浜烘妧鏈崥瀹紝铻嶅悎浠ｇ爜鏁欏涓庣敓娲昏褰曘€傝繎鏈熶笓娉ㄤ簬Python/C++/绠楁硶涓€瀵逛竴杈呭锛屽垎浜獶eepSeek妯″瀷瀹炴搷銆佷俊鎭ゥ璧涢瑙ｅ強鎽勫奖璇剧▼锛屽苟鎺ㄥ嚭楂樿€冨織鎰垮～鎶ユ寚鍗椼€傛妧鏈笓鏍忔兜鐩朒exo榄旀敼銆佽嚜鍔ㄥ寲鑴氭湰寮€鍙戯紙濡傝嚜鍔ㄧ敓鎴愭枃绔犲厓鏁版嵁锛夛紝鐢熸椿鏉垮潡璁板綍鑲插効鏃ュ父锛堢櫨澶╂媿鐓ц鍒掋€佹瘝濠寸敤鍝佹竻鍗曪級涓庡搴晠浜嬨€傞鏍煎菇榛樻帴鍦版皵锛岄€氳繃浠ｇ爜妗堜緥涓庡疄鎴樼粡楠岄檷浣庡涔犻棬妲涳紝鍚屾椂寮€杈熸帴鍗曟笭閬擄紝鎻愪緵浣滀笟浠ｅ啓鏈嶅姟锛屽睍鐜版瀬瀹笌濂剁埜鐨勫弻閲嶈韩浠姐€?,
			},
			{
				author: '鏄撹埅',
				sitenick: '',
				title: '鏄撹埅',
				desc: '涓€鍚嶇紪绋嬬埍濂借€呯殑鍗氬锛岃褰曚笌鍒嗕韩缂栫▼銆佸涔犱腑鐨勭煡璇嗙偣',
				link: 'https://blog.yihang.info/',
				feed: 'https://blog.yihang.info/feed/',
				icon: 'https://blog.yihang.info/favicon.ico',
				avatar: 'https://blog.yihang.info/favicon.ico',
				archs: ['Typecho', '鏈嶅姟鍣?],
				date: '2024-12-09',
				comment: '鏄撹埅鍗氬锛坆log.yihang.info锛?025骞?2鏈堟寔缁洿鏂帮紝鑱氱劍鎶€鏈鍩熴€傚垎浜玃HP鏂扮増鏈壒鎬с€乄eb鍓嶇浼樺寲绛夋暀绋嬶紝鎻愪緵鏀粯绯荤粺銆佽亰澶╃郴缁熺瓑婧愮爜璧勬簮锛岃繕娑电洊鏁扮爜鏂伴椈銆佺綉缁滃畨鍏ㄥ伐鍏锋帹鑽愶紝瀹炵敤骞茶揣涓板瘜銆?,
			},
			{
				author: '灏忕背閲岀殑澶ч害',
				sitenick: '',
				title: '灏忕背閲岀殑澶ч害',
				desc: '鑺濆叞鐢熶簬娣辫胺锛屼笉浠ユ棤浜鸿€屼笉鑺炽€?,
				link: 'https://www.minbit.top/',
				feed: 'https://www.minbit.top/atom.xml',
				icon: 'https://i.p-i.vip/135/20251129-692a6d093173d.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6d093173d.png',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '鈥滃皬绫抽噷鐨勫ぇ楹︹€濈殑鍗氬锛坵ww.minbit.top锛?025骞存寔缁洿鏂帮紝鏈妗堜絾鎻愪緵澶氬姞閫熷煙鍚嶃€傝仛鐒︽妧鏈鍩燂紝鍒嗕韩C++ STL銆丩inux銆丮ySQL銆佺畻娉曠瓑骞茶揣锛屼篃鏈塁hatGPT Go濂楅绛夊疄鐢ㄨ祫婧愶紝鏄褰曞涔犱笌鎶€鏈垎浜殑骞冲彴銆?,
			},
			{
				author: 'Evilrabbit',
				sitenick: '',
				title: 'Evilrabbit',
				desc: '鐖?Coding 鐖辩敓娲?,
				link: 'https://blog.yujiay.wang/',
				feed: 'https://blog.yujiay.wang/atom.xml',
				icon: 'https://blog.yujiay.wang/images/site/BlogHsvg.png',
				avatar: 'https://blog.yujiay.wang/images/site/BlogHsvg.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'Evilrabbit Blog锛坆log.yujiay.wang锛?025骞存寔缁洿鏂帮紝鍐呭澶氬厓銆傛兜鐩栨妧鏈疄璺碉紙Hexo鐏板害鍙戝竷銆佷富棰樼編鍖栵級銆佺‖浠舵姌鑵俱€丄I涓庣綉缁滃畨鍏紝涔熸湁绉戞妧鍦堝姩鎬併€佺敓娲诲垎浜瓑锛屽吋鍏锋妧鏈共璐т笌鐢熸椿鎰熸偀锛屽疄鐢ㄤ笖涓板瘜銆?,
			},
			{
				author: 'lololowe',
				sitenick: '',
				title: 'lololowe',
				desc: '璁＄綉锛岀綉瀹夌煡璇嗗垎浜?,
				link: 'https://blog.lololowe.com/',
				feed: 'https://blog.lololowe.com/atom.xml',
				icon: 'https://blog.lololowe.com/favicon.ico',
				avatar: 'https://blog.lololowe.com/favicon.ico',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'lololowe鐨勫崥瀹㈡槸鎶€鏈埍濂借€卨ololowe鐨勬伂娣℃妧鏈┖闂达紝娣辫€曠綉缁滃畨鍏ㄤ笌缃戠粶宸ョ▼棰嗗煙銆傝繎鏈熻仛鐒penStack蹇€熼儴缃插疄鎴樸€丆hrome娴忚鍣ㄦ€ц兘浼樺寲銆佺綉缁滃崗璁В鏋愶紙MTU/閾捐矾妫€娴?BFD锛夌瓑纭牳鎶€鏈紝鍚屾椂鍒嗕韩鐜閰嶇疆蹇冨緱涓庡瓨鍌ㄦ妧鏈柟妗堛€傛妧鏈笓鏍忔兜鐩朠ython鑷姩鍖栬剼鏈€丏ocker瀹瑰櫒鍖栭儴缃层€丩inux绯荤粺璋冧紭绛夊疄鎴樺唴瀹癸紝椋庢牸鏈村疄娉ㄩ噸瀹炴搷锛岄€氳繃浠ｇ爜鐗囨涓庡師鐞嗗浘瑙ｉ檷浣庡鏉傚崗璁悊瑙ｉ棬妲涳紝鏄綉缁滃伐绋嬪笀涓庤繍缁翠汉鍛樼殑瀹炵敤宸ュ叿搴撱€?,
			},
			{
				author: '闈欒灏忕獥',
				sitenick: '',
				title: '闈欒灏忕獥',
				desc: '绐楀鏄摑澶╃櫧浜戯紝蹇冮噷鏄皬鏉忔墘闂淬€?,
				link: 'https://www.vindo.cn/',
				feed: 'https://www.vindo.cn/feed.xml',
				icon: 'https://img.vindo.cn/AVATOR.png',
				avatar: 'https://img.vindo.cn/AVATOR.png',
				archs: ['Vue', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'Vindo鐨勪釜浜哄崥瀹㈣仛鐒︽妧鏈笌浜烘枃浜ょ粐鐨勫鍏冮鍩燂紝灞曠幇寮€鍙戣€呬笌鍘嗗彶鐖卞ソ鑰呯殑璺ㄧ晫瑙嗚銆傝繎鏈熸枃绔犳兜鐩栥€婃瀯寤虹綉缁滃弸閭诲鎶椾俊鎭導鎴裤€嬬殑Web鐢熸€佹€濊€冦€併€夿logsClub涓枃鍗氬鑱旂洘銆嬬殑绀惧尯瀹炶返瑙傚療锛屼互鍙娿€婃枃鍖栭殣鍠诲浣曞閫犺鐭ャ€嬬殑娣卞害涔﹁瘎锛屽苟鍒嗕韩浜嗐€婁竴閿嚜鍔ㄥ寲鍥剧墖鍘嬬缉宸ュ叿銆嬬瓑鎶€鏈共璐с€備綔涓虹粏鑺傛帶涓庡鍙ゆ儏鎬€鎸佹湁鑰咃紙鐥磋糠鍗楀畫缇庡涓嶢rcher璁捐鍝插锛夛紝鎸佺画鎺㈢储骞抽潰璁捐鍒涙柊涓庣嫭绔嬪崥瀹㈢殑鍏辩敓鍙兘锛岃嚧鍔涗簬鍦ˋI娴疆涓畧鎶ゅ唴瀹规俯搴︺€?,
			},
			{
				author: 'bbb-lsy07',
				sitenick: '',
				title: 'bbb-lsy07',
				desc: '绉戞妧婵€鑽′汉鏂囷紝娲炶鏅烘収鏈湡銆?,
				link: 'https://blog.6uu.us/',
				feed: 'https://blog.6uu.us/rss.xml',
				icon: 'https://blog.6uu.us/upload/00000.png',
				avatar: 'https://blog.6uu.us/upload/00000.png',
				archs: ['Halo', 'EdgeOne'],
				date: '2024-12-09',
				comment: 'bbb-lsy07鐨勫崥瀹紙blog.6uu.us锛?025骞?1鏈堟寔缁洿鏂帮紝鑱氱劍瀹炵敤鎶€鏈€傚垎浜湇鍔″櫒鎼缓銆佸崥瀹㈤儴缃层€侀偖绠?缃戠洏鎼缓绛夋暀绋嬶紝鍚湇鍔″櫒娴嬭瘎銆丄I鐩稿叧鍐呭锛屼篃鏈夌爺瀛﹁褰曠瓑鐢熸椿鍒嗕韩锛屽共璐ф弧婊′笖鏄撲笂鎵嬨€?,
			},
			{
				author: '鍛ㄦ鼎鍙?,
				sitenick: '',
				title: '鍛ㄦ鼎鍙?,
				desc: '鏀跺綍寮€婧愶紝濂界敤鐨勪簰鑱旂綉椤圭洰',
				link: 'https://blog.zrf.me/',
				feed: 'https://blog.zrf.me/atom.xml',
				icon: 'https://image.lolimi.cn/2025/10/07/68e472302fe55.png',
				avatar: 'https://image.lolimi.cn/2025/10/07/68e472302fe55.png',
				archs: ['Hexo', 'Cloudflare'],
				date: '2024-12-09',
				comment: '鍛ㄦ鼎鍙戝崥瀹㈡槸鎶€鏈瀬瀹笌鐢熸椿瑙傚療鑰呯殑璺ㄧ晫绌洪棿锛岃仛鐒﹀紑婧愬伐鍏蜂笌浜掕仈缃戝疄鐢ㄩ」鐩垎浜€傝繎鏈熸繁搴︽祴璇凜loudflare杈圭紭璇佷功閮ㄧ讲銆乂ercel鍔犻€熶紭鍖栫瓑纭牳鎶€鏈紝鎻涓存椂閭鎼缓銆佽闃呴摼鎺ヨ仛鍚堢瓑寮€鍙戣€呭垰闇€锛屽苟璁板綍鎹㈢數姹犵炕杞︺€佸煙鍚嶆姠娉ㄧ瓑瓒ｅ懗鏃ュ父銆傚唴瀹规í璺ㄧ綉缁滃畨鍏ㄣ€佺郴缁熻皟浼樸€丄I搴旂敤绛夐鍩燂紝椋庢牸鍔″疄鎺ュ湴姘旓紝閫氳繃浠ｇ爜鐗囨涓庡疄鎿嶆寚鍗楅檷浣庢妧鏈棬妲涳紝鍚屾椂浠ュ菇榛樼瑪瑙︽秷瑙ｅ伐鍏风悊鎬э紝鏄瀬瀹㈠湀鐨勫疂钘忓伐鍏峰簱涓庢不鎰堢郴绮剧瑙掕惤銆?,
			},
			{
				author: '鎷ユ姳鏃ュ嚭鐨勫皬灞?,
				sitenick: '',
				title: '鎷ユ姳鏃ュ嚭鐨勫皬灞?,
				desc: '鎷ユ姳鏃ュ嚭锛屼篃鎷ユ姳鐢熸椿',
				link: 'https://blog.ybrc.top/',
				feed: 'https://blog.ybrc.top/feed.xml',
				icon: 'https://blog.ybrc.top/upload/logo.jpg',
				avatar: 'https://blog.ybrc.top/upload/logo.jpg',
				archs: ['Halo', '鏈嶅姟鍣?],
				date: '2024-12-09',
				comment: '鎷ユ姳鏃ュ嚭鐨勫皬灞?025骞磋褰曠珯闀垮涓氳浆鎶樹笌楂樹腑閫傚簲锛屽勾鏈綔骞村害鎬荤粨銆佹湡璁?026銆傚唴瀹瑰鍏冿紝鍚玁ezha鐩戞帶銆佸疂濉斾富棰樻洿鎹㈢瓑鎶€鏈暀绋嬶紝鏈嶅姟鍣ㄧ姸鎬佸睍绀猴紝杩樻湁闅忕瑪銆佸皬璇村垱浣滐紝鍏煎叿瀹炵敤骞茶揣涓庣敓娲绘劅鎮熴€?,
			},
			{
				author: '鍑屽皹',
				sitenick: '',
				title: '鍑屽皹',
				desc: '浜庨珮灞变箣宸咃紝鏂硅澶ф渤濂旀秾锛涗簬缇ゅ嘲涔嬩笂锛屾洿瑙夐暱椋庢旦鑽°€?,
				link: 'https://b.icxk.cn/',
				feed: '',
				icon: 'https://i.p-i.vip/135/20251129-692a6c95625e8.png',
				avatar: 'https://i.p-i.vip/135/20251129-692a6c95625e8.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '鍑屽皹k鐨勫崥瀹?024-2025骞存寔缁洿鏂帮紝鑱氱劍鎶€鏈紑鍙戜笌鏃ュ父鍒嗕韩銆傛妧鏈笂娑电洊CSS鐗规晥銆丠exo榄旀敼銆佹湇鍔″櫒鎼缓锛圡inecraft銆侀潤鎬佺綉绔欙級銆佸浘搴婃惌寤虹瓑瀹炵敤鏁欑▼锛屼篃璁板綍杞憲鐢宠銆侀ギ閰掕绠楀櫒绛夌敓娲荤偣婊达紝骞茶揣涓庢棩甯稿吋鍏枫€?,
			},
			{
				author: 'snows_l',
				sitenick: '',
				title: 'snows_l',
				desc: '灏忓緱鐩堟弧锛?,
				link: 'http://snows-l.site/',
				feed: '',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=37523953&s=640',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=37523953&s=640',
				archs: ['PHP', '鏈嶅姟鍣?],
				date: '2024-12-09',
				comment: '鐩墠鍏紑淇℃伅鏈夐檺锛屾殏鏈姭闇茬珯闀胯繎鏈熷姩鎬佸強鍏蜂綋鏂囩珷鍐呭銆侀鍩熸柟鍚戯紝浠呰兘纭鍗氬鍚嶇О鍙婅闂煙鍚嶏紝鍚庣画鍙叧娉ㄥ叾鏇存柊浠ヤ簡瑙ｆ洿澶氳鎯呫€?,
			},
			{
				author: '姊ㄥ敖鍏?,
				sitenick: '',
				title: '姊ㄥ敖鍏?,
				desc: 'A place for peace',
				link: 'https://blog.ljx.icu/',
				feed: 'https://blog.ljx.icu/rss.xml',
				icon: 'https://image.lolimi.cn/2026/02/08/6987f1a84ed12.webp',
				avatar: 'https://image.lolimi.cn/2026/02/08/6987f1a84ed12.webp',
				archs: ['Astro', '鍥藉唴 CDN'],
				date: '2024-12-09',
				comment: '鐢卞鐢烲jx杩愯惀锛?025骞存寔缁洿鏂拌嚦12鏈堛€傝仛鐒︽妧鏈疄鎿嶏紝鍒嗕韩Astro AI鎽樿銆佸崥瀹㈤儴缃层€丄PI浣跨敤绛夊共璐э紝涔熸帹鑽怗itHub鏈夎叮椤圭洰锛屽吋椤惧叏缃戠儹姒滆仛鍚堜笌鐢熸椿鍚愭Ы锛屽唴瀹瑰疄鐢ㄤ笖澶氬厓銆?,
			},
			{
				author: 'JustPureH20',
				sitenick: '',
				title: 'JustPureH2O',
				desc: '绌锋柟鍦嗗钩鐩翠箣鎯咃紝灏借鐭╁噯缁充箣鐢?,
				link: 'https://justpureh2o.cn/',
				feed: '',
				icon: 'https://pic.wudu.ltd/pic/2025/12/12/693bfade6a038.jpg',
				avatar: 'https://pic.wudu.ltd/pic/2025/12/12/693bfade6a038.jpg',
				archs: ['Hexo', 'Vercel'],
				date: '2024-12-09',
				comment: '鐢遍珮涓夊瀛愯繍钀ワ紝2024-2025 骞存寔缁洿鏂般€傝仛鐒﹂珮涓鑰冧笌瀛︿範骞茶揣锛屾兜鐩栨暟鐗╁寲鐢熻鏂囨牳蹇冪煡璇嗙偣銆佽В棰樼瓥鐣ワ紝涔熸湁缂栫▼棰樿В銆佺綉鍥炬函婧愮瓑鍐呭锛岃繕璁板綍鍗氬鏂板姛鑳芥瀯鎯筹紝瀹炵敤涓旇创鍚堝鐢熼渶姹傘€?,
			},
			{
				author: '閰ョ背鐨勫皬绔?,
				sitenick: '',
				title: '閰ョ背鐨勫皬绔?,
				desc: '缁堟湁涓€鏃ワ紝瀵绘ⅵ涓汉',
				link: 'https://www.sumi233.top/',
				feed: 'https://www.sumi233.top/atom.xml',
				icon: 'https://jsd.qixz.cn/gh/huang233893/blog-image-bed@main/top/huang233893/imgs/blog/usersumi.png',
				avatar: 'https://jsd.qixz.cn/gh/huang233893/blog-image-bed@main/top/huang233893/imgs/blog/usersumi.png',
				archs: ['Hexo', 'EdgeOne'],
				date: '2024-12-09',
				comment: '2025 骞存湯鎸佺画鏇存柊锛岀珯闀垮垰鎴愬勾銆佸鎴橀珮鑱岃€冦€傚唴瀹逛互鐢熸椿纰庣蹇典负涓伙紝璁板綍鏃呮父銆佹墦宸ャ€佹父鎴忔棩甯革紝涔熷垎浜?Windows 鏇存柊鏃ュ織銆佹槦闇茶胺鏃犳樉鍗℃湇鍔″櫒鎼缓绛夊疄鐢ㄦ暀绋嬶紝娓╅Θ鍙堟湁骞茶揣銆?,
			},
			{
				author: 'Tavre',
				sitenick: '',
				title: 'Tavre',
				desc: '鑼尗澶ф捣 鎴戜笌浣犵浉閬?,
				link: 'https://blog.tavr.top/',
				feed: 'https://blog.tavr.top/rss.xml',
				icon: 'https://q1.qlogo.cn/g?b=qq&nk=2987304764&s=640',
				avatar: 'https://q1.qlogo.cn/g?b=qq&nk=2987304764&s=640',
				archs: ['Astro', 'Vercel'],
				date: '2024-12-09',
				comment: '2025 骞存寔缁洿鏂帮紝绔欓暱涓洪珮涓敓銆傚唴瀹规兜鐩栧疄鐢ㄦ妧鏈暀绋嬶紙瀹濆涓撲笟鐗堢敵璇枫€佸厤璐瑰浘搴婃惌寤恒€丄I 缁樼敾銆佸埛璇捐剼鏈級锛屼篃鍒嗕韩婢庢箖 OS 浣跨敤浣撻獙銆丆SGO 娓告垙鏃ュ父锛屽共璐т笌鐢熸椿璁板綍鍏煎叿锛屾€т环姣旈珮銆?,
			},
			{
				author: 'Liushen',
				sitenick: '娓呯窘椋炴壃',
				title: '娓呯窘椋炴壃',
				desc: '鏌冲奖鏇虫洺锛屾竻閰掑鐏紝鎵瑪鎾掑ⅷ锛屽績澧冨闇?,
				link: 'https://blog.liushen.fun/',
				feed: 'https://blog.liushen.fun/atom.xml',
				icon: 'https://blog.liushen.fun/favicon.ico',
				avatar: 'https://q.qlogo.cn/g?b=qq&nk=3162475700&s=640',
				archs: ['Hexo', 'EdgeOne'],
				date: '2025-01-01',
				comment: '杩戞湡鍦ㄦ垚閮芥椿鍔ㄣ€佸 C++锛屾浘鎰熷啋銆傛枃绔犲娑?Hexo/Butterfly 涓婚榄旀敼銆丄nheyu-App 閮ㄧ讲銆乀inyAuth 璁よ瘉绛夌瓚绔欒繍缁村唴瀹癸紝涔熸湁鏃呮父銆佽褰辩被闂叉儏鏉傝銆?,
			},
			{
				author: 'THW',
				sitenick: '',
				title: 'THW鈥檚 Blog',
				desc: '鍓嶉€斾技娴凤紝鏉ユ棩鏂归暱',
				link: 'https://blog.tianhw.top/',
				feed: 'https://blog.tianhw.top/rss.xml',
				icon: 'https://image.tianhw.top/avatar.webp',
				avatar: 'https://image.tianhw.top/avatar.webp',
				archs: ['Astro', 'EdgeOne'],
				date: '2026-01-18',
				comment: '鑱氱劍Web寮€鍙戜笌浜戝師鐢熼鍩燂紝杩戞湡鍥寸粫EdgeOne Pages銆丄stro闈欐€佺敓鎴愮瓑宸ュ叿灞曞紑娣卞害瀹炶返锛屽垎浜嚜鍔ㄥ寲鍥惧簥鏋勫缓銆佷竴閿儴缃叉柟妗堛€佺函鍓嶇IP鑾峰彇绛夌‖鏍告暀绋嬨€?,
			},
			{
				author: 'Elykia',
				sitenick: '',
				title: 'Elykia',
				desc: '鑷翠互鏃犵憰涔嬩汉',
				link: 'https://blog.elykia.cn/',
				feed: 'https://blog.elykia.cn/atom.xml',
				icon: 'https://bu.dusays.com/2024/10/25/671b2438203a6.gif',
				avatar: 'https://bu.dusays.com/2024/10/25/671b2438203a6.gif',
				archs: ['Golang', 'EdgeOne'],
				date: '2026-01-23',
				comment: '涓汉鏂囪壓鍝叉€濆崥瀹紝绔欓暱杩戞湡娌夋蹈浜庤瘲鎰忚〃杈句笌鐢熷懡鍝叉€濆垱浣滐紝鏂囩珷澶氭帰璁ㄥ瓨鍦ㄦ剰涔夈€佷汉鎬ф湰璐ㄤ笌鑹烘湳鐤楁剤锛岄鍩熸í璺ㄦ枃瀛︺€佸績鐞嗗涓庡瓨鍦ㄤ富涔夊摬瀛︼紝鏂囬绌虹伒闅芥案锛屼互闅愬柣涓庤瘲鎬ц瑷€鏋勫缓绮剧鏍栧眳鍦帮紝鍦ㄦ暟瀛楁椂浠ｅ畧鎶ゆ€濇兂绾噣鎬с€?,
			},
			{
				author: 'Revelation',
				sitenick: '',
				title: 'Revelation',
				desc: '鎴戝湪绛夊緟锛岀瓑浣犲洖鏉?,
				link: 'https://www.040426.xyz/',
				feed: 'https://www.040426.xyz/atom.xml',
				icon: 'https://image.lolimi.cn/2026/02/08/6987f0ca84a1d.webp',
				avatar: 'https://image.lolimi.cn/2026/02/08/6987f0ca84a1d.webp',
				archs: ['Golang', '鏈嶅姟鍣?],
				date: '2026-01-25',
				comment: '鑱氱劍浜庝釜浣撳湪铏氬涓庣湡瀹為棿鐨勬專鎵庯紝閫氳繃銆婅嫢涓哄亣甯屾湜瀹佹棤甯屾湜銆嬬瓑鏂囨帰璁ㄧ幇浠ｄ汉绮剧鍥板銆傚唴瀹规兜鐩栧瓨鍦ㄤ富涔夊弽鎬濄€佽嚜鎴戣В鏋勪笌閲嶅缓锛岄鍩熸秹鍙婂摬瀛︽€濊鲸銆佸績鐏垫垚闀夸笌鏂囧鎬хぞ浼氳瀵燂紝鏂囬鍐峰郴鐘€鍒╃洿鎸囧綋浠ｇ敓瀛樻倴璁恒€?,
			},
			{
				author: 'LanM',
				sitenick: '',
				title: 'LanM',
				desc: '钃濊帗',
				link: 'https://bluelanm.github.io/my-website/',
				feed: 'https://bluelanm.github.io/my-website/rss.xml',
				icon: 'https://image.lolimi.cn/2026/02/05/6984abce1bbaa.webp',
				avatar: 'https://image.lolimi.cn/2026/02/05/6984abce1bbaa.webp',
				archs: ['GitHub Pages', 'HTML'],
				date: '2026-02-05',
				comment: '钃濊帗銇瓸log杩戞湡璋僁ocusaurus閰嶇疆瑙ｅ姞杞介棶棰橈紝璁板缓绔欏疄璺碉紝娑夋妧鏈缓绔欍€佷釜浜哄疄璺碉紝鏂囬鍔″疄銆?,
			},
			{
				author: 'Karina',
				sitenick: '灏忕獫',
				title: '鐞崇惓鐨勫皬绐?,
				desc: '鐞崇惓鐨勫皬绐?,
				link: 'https://karina.xin/',
				feed: 'https://blog.karina.xin/rss.xml',
				icon: 'https://image.lolimi.cn/2026/02/08/6987ef9f14f0a.webp',
				avatar: 'https://image.lolimi.cn/2026/02/08/6987ef9f14f0a.webp',
				archs: ['GitHub Pages', 'HTML'],
				date: '2026-02-08',
				comment: '杩戝喌鍚獹ithub椤圭洰銆丵Q缇ゃ€傚唴瀹规湁鏃ヨ銆佹€濊€冦€佺鎶€鏁扮爜鏈€佹潅璋堬紝娑夊摬瀛︾巹瀛︺€佽姊︾粯鐢伙紝鏂囬甯﹀柕绯诲彲鐖便€?,
			},
		],
	},
	// #endregion
] satisfies FeedGroup[]
